### ISSUE TITLE
Xootd IPV6 transfer fails with (General problem: Unable to find address that faces lxplus730.cern.ch/2001:1458:d00:12:0:0:0:270 [666]) (source)

### ISSUE THREAD

**Issue by cfgamboa** [dCache/dcache#6605] opened 2022-04-22 22:09 UTC
Hello,

IPV6 transfer to the BNL DUNE instance is failing while using Xrootd protocol. Other protocols like DAV works fine with IPV6 and IPV4. The error reported here is different to the one reported on https://github.com/dCache/dcache/issues/6602

The following is the transfer test:
```
[cgamboa@lxplus730 ~]$ xrdcp -f -DSNetworkStack IPv6 root://dcdndoor01.sdcc.bnl.gov:1096/pnfs/sdcc.bnl.gov/data/dune/1gbtestfile.20210413_6b /tmp/IPV6DUNE
[0B/0B][100%][==================================================][0B/s]  
Run: [ERROR] Server responded with an error: [3012] Failed to open file (General problem: Unable to find address that faces lxplus730.cern.ch/2001:1458:d00:12:0:0:0:270 [666]) (source)

````
The XRoot door log 
```
22 Apr 2022 17:46:28 [pool-7-thread-8] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXdRShqgkA] Redirecting to dcdn001.sdcc.bnl.gov, dcdn001.sdcc.bnl.gov/10.38.5.10:33207
22 Apr 2022 17:46:28 [pool-7-thread-8] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXdRShqgkA] Sending the following host information to the client: dcdn001.sdcc.bnl.gov
22 Apr 2022 17:46:58 [xrootd-net-4] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXdRSp6ZuA] Time since last server cert refresh 34577
22 Apr 2022 17:46:59 [xrootd-net-4] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXdRSp6ZuA] Client protocol version was 10600, using GSIPost49ServerRequestHandler.
22 Apr 2022 17:46:59 [xrootd-net-4] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXdRSp6ZuA] Time since last server cert refresh 35659
22 Apr 2022 17:47:00 [xrootd-net-4] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXdRSp6ZuA] Using padded DH secret generation.
22 Apr 2022 17:47:00 [pool-7-thread-8] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXdRSp6ZuA] Opening pnfs/sdcc.bnl.gov/data/dune/1gbtestfile.20210413_6b for read
22 Apr 2022 17:47:00 [pool-7-thread-8] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXdRSp6ZuA] OPAQUE : {}
22 Apr 2022 17:47:00 [Xrootd-dcdndoor01-0] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXdRSp6ZuA dcdn001_1 DoorTransferFinished 0000DB68763F43B54FA2B6AAEE9ED2287B53] Transfer 0000DB68763F43B54FA2B6AAEE9ED2287B53@PoolName=dcdn001_1 PoolAddress=dcdn001_1@dcdn001oneDomain failed: General problem: Unable to find address that faces lxplus730.cern.ch/2001:1458:d00:12:0:0:0:270 (error code=666)
22 Apr 2022 17:47:00 [pool-7-thread-8] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXdRSp6ZuA] Xrootd-Error-Response: ErrorNr=3012 ErrorMsg=Failed to open file (General problem: Unable to find address that faces lxplus730.cern.ch/2001:1458:d00:12:0:0:0:270 [666])
```
I have attached the entire log for the xrootd transfer `-d 3` 

The dune door is resolve as:
```

[cgamboa@lxplus730 ~]$ nslookup dcdndoor01.sdcc.bnl.gov
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	dcdndoor01.sdcc.bnl.gov
Address: 192.33.128.30
Name:	dcdndoor01.sdcc.bnl.gov
Address: 2620:0:210:2::1e
```

dcache on doors 7.2.15, other components are 7.2.1

Currently the pools are local to BNL so it is expected the transfer fails as the pools are not externally accessible. However, if using the IPV4 protocol to request the transfer the error is different to the one reported.

Here the error is related to the redirection.

```
[cgamboa@lxplus730 ~]$ xrdcp -f -DSNetworkStack IPv4 root://dcdndoor01.sdcc.bnl.gov:1096/pnfs/sdcc.bnl.gov/data/dune/1gbtestfile.20210413_6b /tmp/IPV4DUNE
[0B/0B][100%][==================================================][0B/s]  
Run: [FATAL] Redirect limit has been reached:  (source)
```

From the door log is shown that there is a redirection to the pool (which is not externally accessible)
```
22 Apr 2022 18:04:07 [pool-7-thread-14] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXdRWeDdoA] Redirecting to dcdn001.sdcc.bnl.gov, dcdn001.sdcc.bnl.gov/10.38.5.10:33217
```

So the question is why IPV6 attempt does not have the same behavior than IPV4. I was expecting that both IP protocols should fail with the same error. `Redirect limit has been reached:  (source)`

Thank you,

Carlos

**Comment by alrossi** [comment] 2022-05-04 14:10
@cfgamboa @DmitryLitvintsev 

Carlos,

I do believe this is related to both #6658 and #6602.

I suggest we tackle one issue at a time.  I would suggest starting with getting #6658 to work as we suggested.

If you need us to zoom again with you, please let us know.

Thanks, Al

**Comment by cfgamboa** [comment] 2022-05-04 22:01
Hello Al,

I think a zoom meeting will be go to touch base again. Tomorrow I will be able to meet in the afternoon 2-4pm 

Yes I think is a good idea to tackle one at the time. Please note that I have created the record on GitHub while stepping on those so we can trace them.

All the best,
Carlos

**Comment by alrossi** [comment] 2022-05-05 13:49
(I'm not sure this reply got through, so I'm posting it again here.)


Hello Carlos,

I would like Dmitry to be present as well, since he has contributed to these discussions and may have some further insight from production here at FNAL.

Today we have an operations meeting at 13,00 CDT (14,00 EDT).  It might be feasible to meet after that (14,00 CDT / 15,00 EDT).

I don't recall what the zoom connection was ... did you provide it, or did Dmitry?

Cheers,

**Comment by DmitryLitvintsev** [comment] 2022-05-05 15:13
Hi Carlos,

yeah, I confirm. Go ahead and send the link. But just to make sure, we will be discussing your
pool manager DMZ issue not the issue on this ticket.
My goal is : BNL has to have a poolmanager setup that allows hop from internal to DMZ pools for
transfers. Because this seems the proper solution for DMZ/internal separation.

Dmitry

________________________________________

**Comment by alrossi** [comment] 2022-05-05 17:01
OK, so in the case of IPv6, the pool, which is trying to send its address to the door, cannot find its own local address that is accessible by the client.   It is the same problem but in reverse.  The IPv6 issue simply masks the redirect issue because it happens when the mover is started (before the reply to the client to redirect to the pool).

I'm wondering whether defining link local is what you need on the pools (this is a wild guess).

**Comment by DmitryLitvintsev** [comment] 2022-05-05 17:17
I suggested to add IP/host resolution to '"/etc/hosts" on pool nodes like we do at Fermilab
Has this been tried?

________________________________________

**Comment by cfgamboa** [comment] 2022-05-05 17:18
Yes

**Comment by DmitryLitvintsev** [comment] 2022-05-05 17:27
I think, though, that needs to be tried after files can be delivered from DMZ pools.
"Unable to find address that faces". In this scenario the replica of file you are trying to
access is on "internal" pool. IMO this is compounding the issue.

So first access to DMZ needs to be resolved. Then IPv6 looked at.

________________________________________

**Comment by cfgamboa** [comment] 2022-05-18 19:18
@DmitryLitvintsev @alrossi 

Besides the issue of not been able to contact the internal pool. Currently that pool (internal) do not support IPV6, so it is likely that this error: 
```
Run: [ERROR] Server responded with an error: [3012] Failed to open file (General problem: Unable to find address that faces lxplus730.cern.ch/2001:1458:d00:12:0:0:0:270 [666]) (source)
```
Is due to this, on contrary: I enabled the DMZ READ/WRITE to internal pool configuration explored for QOS on dCache RT( www.dcache.org #10308) on this DUNE instance. 
I was able to READ a file from the dune 

```
[cgamboa@lxplus721 ~]$ xrdcp -f root://dcdndoor01.sdcc.bnl.gov:1096/pnfs/sdcc.bnl.gov/data/dune/1gbtestfile.20210413_6b /dev/null
[976.6MB/976.6MB][100%][==================================================][25.04MB/s]  
```

For IPV6
```
[cgamboa@lxplus721 ~]$ xrdcp -f -DSNetworkStack IPv6 root://dcdndoor01.sdcc.bnl.gov:1096/pnfs/sdcc.bnl.gov/data/dune/1gbtestfile.20210413_6b /dev/null
[976.6MB/976.6MB][100%][==================================================][27.9MB/s]  
```
Works, here the DMZ pool will handle the transfer read, the DMZ pool has IPV6 and IPV4 capability. So here the error reported here is not longer observed.

All the best,
Carlos

**Comment by alrossi** [comment] 2022-05-26 16:04
Carlos,

I'm just a bit confused.  Could you perhaps clarify if the last entry is reporting a problem or whether the behavior is as you expect?

thanks, Al

**Comment by alrossi** [comment] 2022-05-26 17:59
Hi Carlos,

So the problem is with the client?  That is, before you enabled IPv6 on the pool, the door was indicating to the client to use IPv4 with the pool to which it was redirected, and it was still using IPv6?  

If so, then this is out of dCache's hands ...

Thanks, Al

**Comment by cfgamboa** [comment] 2022-05-26 18:07
Hi Al,

Before the IPV6 on the internal POOL the error was triggered:
1. General problem: Unable to find address that faces lxplus730.cern.ch/2001:1458:d00:12:0:0:0:270 [666]) (source) 

After enabling IPV6 in the internal pool the issue disappeared.

Note the issue 1. was not observed when using the DMZ READ/WRITE as these pools have IPV6 enabled.

All the best,
Carlos

**Comment by alrossi** [comment] 2022-05-26 18:17
So what we need to see again is the door logging from before the enabling of IPv6, because the client is simply using the address the door gives it.

It seems to me that the question is:  Why is the door reporting an IPv6 address for the pool when the pool is not enabled with IPv6.   

Java uses DNS lookup to find the address.   It also orders them preferentially.   I suspect the door THINKs the IPv6 is valid for the pool.

**Comment by alrossi** [comment] 2022-05-26 18:20
Actually, I take that back.  I think the pool itself reports its address to the door.

**Comment by cfgamboa** [comment] 2022-05-26 18:42
This is the log for the case when IPV6 is enabled. For the only IPV4 it was already reported
```
26 May 2022 14:34:53 [xrootd-net-35] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXf7nIlAwA] Time since last server cert refresh 11627579
26 May 2022 14:34:53 [xrootd-net-35] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXf7nIlAwA] Loading server certificates. Current refresh interval: 60000 ms
26 May 2022 14:34:53 [xrootd-net-35] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXf7nIlAwA] Verifying host certificate
26 May 2022 14:34:54 [xrootd-net-35] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXf7nIlAwA] Client protocol version was 10600, using GSIPost49ServerRequestHandler.
26 May 2022 14:34:54 [xrootd-net-35] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXf7nIlAwA] Time since last server cert refresh 157
26 May 2022 14:34:54 [xrootd-net-35] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXf7nIlAwA] Using padded DH secret generation.
26 May 2022 14:34:54 [pool-7-thread-76] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXf7nIlAwA] Opening pnfs/sdcc.bnl.gov/data/test/test_root.txt for read
26 May 2022 14:34:54 [pool-7-thread-76] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXf7nIlAwA] OPAQUE : {}
26 May 2022 14:34:54 [pool-7-thread-76] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXf7nIlAwA] Unable to resolve IP address 2620:0:210:880a:0:0:0:10 to a canonical name
26 May 2022 14:34:54 [pool-7-thread-76] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXf7nIlAwA] Redirecting to 2620:0:210:880a:0:0:0:10, 2620:0:210:880a:0:0:0:10/2620:0:210:880a:0:0:0:10:33315
26 May 2022 14:34:54 [pool-7-thread-76] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXf7nIlAwA] Sending the following host information to the client: 2620:0:210:880a:0:0:0:10
```
All the best,
Carlos

**Comment by cfgamboa** [comment] 2022-05-26 18:46
Since the pool only supportted IPV4 the transfer should have used IPV4.

**Comment by DmitryLitvintsev** [comment] 2022-05-26 18:48
Carlos,

in this case adding IPV4 -> name resolution "/etc/hosts" would have helped. I think. 

Dmitry

**Comment by cfgamboa** [comment] 2022-05-26 18:48
It was enbled

**Comment by alrossi** [comment] 2022-05-26 18:52
```Since the pool only supportted IPV4 the transfer should have used IPV4.```

I agree.  The problem I trying to determine is whether this is an xrootd (SLAC) issue or a dCache one.

**Comment by alrossi** [comment] 2022-05-26 19:51
Carlos,

It is my opinion that the problem still lies with your system's network configuration.

In the above case of IPv4, you see:

```
22 Apr 2022 17:46:28 [pool-7-thread-8] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXdRShqgkA] Redirecting to dcdn001.sdcc.bnl.gov, dcdn001.sdcc.bnl.gov/10.38.5.10:33207
22 Apr 2022 17:46:28 [pool-7-thread-8] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXdRShqgkA] Sending the following host information to the client: dcdn001.sdcc.bnl.gov
```

but in the case of IPv6, you see:

```
26 May 2022 14:34:54 [pool-7-thread-76] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXf7nIlAwA] Unable to resolve IP address 2620:0:210:880a:0:0:0:10 to a canonical name
26 May 2022 14:34:54 [pool-7-thread-76] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXf7nIlAwA] Redirecting to 2620:0:210:880a:0:0:0:10, 2620:0:210:880a:0:0:0:10/2620:0:210:880a:0:0:0:10:33315
26 May 2022 14:34:54 [pool-7-thread-76] [door:Xrootd-dcdndoor01@xrootd-dcdndoor01Domain:AAXf7nIlAwA] Sending the following host information to the client: 2620:0:210:880a:0:0:0:10
```

The door is telling you there is something wrong with the DNS lookup.   

Now compare this to one of the FNAL doors:  

```
26 May 2022 14:40:11 [pool-8-thread-402262] [door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXf7UGiClg] Redirecting to stkendca1812.fnal.gov, stkendca1812.fnal.gov/131.225.69.91:22092
26 May 2022 14:40:11 [pool-8-thread-402262] [door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXf7UGiClg] Sending the following host information to the client: stkendca1812.fnal.gov
26 May 2022 14:40:11 [pool-8-thread-402283] [door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXf7FUgATA] Redirecting to stkendca1909.fnal.gov, stkendca1909.fnal.gov/2620:6a:0:4812:f0:0:69:112:24915
26 May 2022 14:40:11 [pool-8-thread-402283] [door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXf7FUgATA] Sending the following host information to the client: stkendca1909.fnal.gov
26 May 2022 14:40:11 [pool-8-thread-402265] [door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXf7yQApKg] Redirecting to stkendca1913.fnal.gov, stkendca1913.fnal.gov/2620:6a:0:4812:f0:0:69:116:20094
26 May 2022 14:40:11 [pool-8-thread-402265] [door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXf7yQApKg] Sending the following host information to the client: stkendca1913.fnal.gov
26 May 2022 14:40:11 [pool-8-thread-402092] [door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXf70Fx57g] Redirecting to stkendca1910.fnal.gov, stkendca1910.fnal.gov/131.225.69.113:20648
26 May 2022 14:40:11 [pool-8-thread-402092] [door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXf70Fx57g] Sending the following host information to the client: stkendca1910.fnal.gov
26 May 2022 14:40:11 [pool-8-thread-402272] [door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXf7jal/mA] Redirecting to stkendca1802.fnal.gov, stkendca1802.fnal.gov/131.225.69.81:20670
26 May 2022 14:40:11 [pool-8-thread-402272] [door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXf7jal/mA] Sending the following host information to the client: stkendca1802.fnal.gov
26 May 2022 14:40:11 [pool-8-thread-402250] [door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXf7aYDOtA] Redirecting to stkendca1909.fnal.gov, stkendca1909.fnal.gov/2620:6a:0:4812:f0:0:69:112:24915
26 May 2022 14:40:11 [pool-8-thread-402250] [door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXf7aYDOtA] Sending the following host information to the client: stkendca1909.fnal.gov
```

From the above, you will see that IPv6 addresses are equally well resolved to the hostname as are IPv4.

The client should, in any case, be receiving a hostname, not an address.   This is because of the requirement that IP addresses be in the alternate names of the host certificate in order for TLS to work.  Rather than obligating sites to do this for all their certs, it was decided that xroot always attempt to return the host name.   Here is the code:  

```
            /*
             * ok, open was successful
             */
            InetSocketAddress address = transfer.getRedirect();

            /*
             *  Do not use the IP address as host name, as this will block
             *  TLS from working.
             *
             *  According to https://tools.ietf.org/html/rfc5280#section-4.2.1.6
             *  an IP is required to be in the list of Subject Alternative Names
             *  in the host certificate, but these are rarely added in practice.
             *  TLS enforces the RFC and this is a workaround.
             */
            String host = address.getHostName();
            if (InetAddresses.isInetAddress(host)) {
                _log.warn("Unable to resolve IP address {} "
                      + "to a canonical name", host);
            }

            _log.info("Redirecting to {}, {}", host, address);

            return new RedirectResponse<>(req, host, address.getPort(),
```

The irony here is that, peculiar to your setup, the address works (IPv6), but the hostname doesn't.   

But this seems to be symptomatic of a larger configuration issue.   The Java lookup is confused for the IPv6 address on your door and can't find a corresponding hostname for it.

So, in any case, I really do not think this is a specifically dCache issue/bug.

Cheers, Al

**Comment by cfgamboa** [comment] 2022-05-26 22:24
Hi Al,

I think we already discussed this on https://github.com/dCache/dcache/issues/6602
the client does manage to use an IPV4 address and IPV6 ipaddress if given. Here I found out that you could provide the client the IPV6 address of the pool by setting it in the `/etc/hosts` file.
The issue here is different. The issue here is that when the pool only supports IPV4 interface the client should not attempt to redirect to an IPV6. Should either fail or redirect using the IPV4 interface.

All the best,
Carlos

**Comment by alrossi** [comment] 2022-05-27 01:32
Carlos,

You seem to be implying, then, that this is ultimately a client problem (i.e., not dCache).  Have I misunderstood?

My only question then would be how the client could know the pool only supports IPv4 if it is given a hostname as endpoint?  This is what is happening, no?  If it gets an IPv4 address, it works, if I understand your cases/examples in #6602 correctly.  But if it gets a hostname, it fails. 

Are you saying that the client itself maps the hostname it gets to an IPv6 address?  Do you actually see that happening in the client logs? (I apologize if you included this information earlier ... things have become a bit muddled over the past month for me on this issue.)

If so, that is strange, because I was under the impression that the client would not do DNS lookup of its own initiative, because it is insecure (at least that is the SLAC development philosophy); but I may be wrong here ... in any case, how would it know not to use the IPv6 address in such a case?

In any event, can this issue be closed?

Thanks, Al

**Comment by cfgamboa** [comment] 2022-05-27 13:26
Hi Al,

From xrdcp client there is a flag that forces the transfer to use IPV4. This issue is not observed there.
I think the client should be able to do this automatically, select only the method (IPV6|IPV4) that is supported by the pool being used to redirect the transfer.

If this is not a dcache issue it self then this issue could be close. 

All the best,
Carlos

**Comment by alrossi** [comment] 2022-05-27 14:14
OK, Carlos.

I will close this issue then.  But I was wondering, before I do, just for my own curiosity.  Would you be able to repeat the situation where the transfer fails because the pool is IPv4 but the client uses IPv6, but do it with xrdcp debug on? i.e.,

```
xrdcp -d 3 ...
```

And then send me the full log for that failed transfer?   

In particular, I'm looking for when the client establishes the connection to the pool.  

e.g.,

```
[2022-05-27 09:11:49.910631 -0500][Debug  ][PostMaster        ] [stkendca1911.fnal.gov:23912] Found 1 address(es): [::ffff:131.225.69.114]:23912
```

But seeing the full log would be useful to me to understand what the client thinks it is doing.

You can attach that log to the old RT ticket (which we should probably also close).

Thank you so much!

Al

**Comment by cfgamboa** [comment] 2022-05-27 19:07
Hi Al,

Since now the pool supports both protocols I can not reproduce it with this instance.

All the best,
Carlos

**Closed** 2022-05-27 19:09 UTC

**Comment by alrossi** [comment] 2022-10-11 07:51
Hello Carlos,

I would like Dmitry to be present as well, since he has contributed to these discussions and may have some further insight from production here at FNAL.

Today we have an operations meeting at 13,00 CDT (14,00 EDT).  It might be feasible to meet after that (14,00 CDT / 15,00 EDT).

I don't recall what the zoom connection was ... did you provide it, or did Dmitry?

Cheers,

Al

________________________________
