### ISSUE TITLE
TLS fails with CANL and WebDAV for system-test

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#1898] opened 2015-10-18 10:42 UTC
After recent introduction of CANL for TLS/SSL, I am no longer able to upload files using TLS/SSL and curl.

Here is my attempt to upload a file into system-test:

    paul@sparkplug:~$ voms-proxy-info
    subject   : /C=DE/O=GermanGrid/OU=DESY/CN=Alexander Paul Millar/CN=proxy
    issuer    : /C=DE/O=GermanGrid/OU=DESY/CN=Alexander Paul Millar
    identity  : /C=DE/O=GermanGrid/OU=DESY/CN=Alexander Paul Millar
    type      : proxy
    strength  : 1024 bits
    path      : /tmp/x509up_u1000
    timeleft  : 11:51:00
    paul@sparkplug:~$ curl --insecure -E /tmp/x509up_u1000 -T /bin/bash https://localhost:2881/disk/test-1
    curl: (35) Unknown SSL protocol error in connection to localhost:2881 
    paul@sparkplug:~$ 

I've made a [network capture](https://desycloud.desy.de/public.php?service=files&t=1b890c1a48dc5f510f3afaa0b65a1df3) showing the interaction between the client and server.

There are several problems here:

1. the connection fails -- obviously a problem, although it seems this is due to misconfiguration of system-test for my system.

2. the server does not send the SSL alert frame indicating it is rejecting the connection -- I think the server should send such a frame -- otherwise the client cannot know why the connection has been rejected.

3. nothing is logged at warn or info level: I think this merits something logged at info level.

4. Switching on debug-level logging for pinboard, I see the following:

        12:26:34 [jetty-992] [] javax.net.ssl.SSLHandshakeException: General SSLEngine problem
            at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431) ~[na:1.8.0_66-internal]
            at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[na:1.8.0_66-internal]
            at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[na:1.8.0_66-internal]
            at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_66-internal]
            at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_66-internal]
            at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:509) ~[jetty-io-9.3.3.v20150827.jar:9.3.3.v20150827]
            at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:315) [jetty-server-9.3.3.v20150827.jar:9.3.3.v20150827]
            at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:223) [jetty-server-9.3.3.v20150827.jar:9.3.3.v20150827]
            at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245 [jetty-io-9.3.3.v20150827.jar:9.3.3.v20150827]
            at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.3.v20150827.jar:9.3.3.v20150827]
            at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:192) [jetty-io-9.3.3.v20150827.jar:9.3.3.v20150827]
            at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245) [jetty-io-9.3.3.v20150827.jar:9.3.3.v20150827]
            at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.3.v20150827.jar:9.3.3.v20150827]
            at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [jetty-io-9.3.3.v20150827.jar:9.3.3.v20150827]
            at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [jetty-util-9.3.3.v20150827.jar:9.3.3.v20150827]
            at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [jetty-util-9.3.3.v20150827.jar:9.3.3.v20150827]
            at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [jetty-util-9.3.3.v20150827.jar:9.3.3.v20150827]
            at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [jetty-util-9.3.3.v20150827.jar:9.3.3.v20150827]
            at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]
        Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
            at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_66-internal]
            at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728) ~[na:1.8.0_66-internal]
            at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304) ~[na:1.8.0_66-internal]
            at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[na:1.8.0_66-internal]
            at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1882) ~[na:1.8.0_66-internal]
            at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:230) ~[na:1.8.0_66-internal]
            at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[na:1.8.0_66-internal]
            at sun.security.ssl.Handshaker$1.run(Handshaker.java:919) ~[na:1.8.0_66-internal]
            at sun.security.ssl.Handshaker$1.run(Handshaker.java:916) ~[na:1.8.0_66-internal]
            at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66-internal]
            at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369) ~[na:1.8.0_66-internal]
            at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:613) ~[jetty-io-9.3.3.v20150827.jar:9.3.3.v20150827]
            ... 13 common frames omitted
        Caused by: java.security.cert.CertificateException: The peer's certificate with subject's DN CN=proxy,CN=Alexander Paul Millar,OU=DESY,O=GermanGrid,C=DE was rejected. The peer's certificate status is: FAILED The following validation errors were found: error at position 1 in chain, problematic certificate subject: CN=Alexander Paul Millar,OU=DESY,O=GermanGrid,C=DE (category: CRL): No valid CRL was found for the CA which issued the chain Cause: No CRLs found for issuer "CN=GridKa-CA, O=GermanGrid, C=DE"
            at eu.emi.security.authn.x509.helpers.ssl.SSLTrustManager.checkIfTrusted(SSLTrustManager.java:73) ~[canl-1.3.3.jar:1.3.3]
            at eu.emi.security.authn.x509.helpers.ssl.SSLTrustManager.checkClientTrusted(SSLTrustManager.java:51) ~[canl-1.3.3.jar:1.3.3]
            at sun.security.ssl.AbstractTrustManagerWrapper.checkClientTrusted(SSLContextImpl.java:929) ~[na:1.8.0_66-internal]
            at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1869) ~[na:1.8.0_66-internal]
            ... 20 common frames omitted

Here we log a stack-trace, therefore this is a bug.

**Comment by paulmillar** [comment] 2015-10-18 10:53
The patch to switch system-test to `IF_VALID` for all services [here](https://rb.dcache.org/r/8670/) is related, but does not address the problems identified here.

**Comment by gbehrmann** [comment] 2015-10-18 14:04
First of all, a stack trace at debug level is not a bug - we have many places in which we switch to more detailed error logging including stack traces at debug level.

Second, doesn't your CA publish CRLs?

Is (2) actually a regression compared to earlier versions? I would expect this to have nothing to do with CANL and more with Jetty and/or Java's TLS implementation.

Indeed, rejection due to absent CRL should be logged at WARN level on the server (since it is a server side issue).

**Comment by gbehrmann** [comment] 2015-10-18 14:32
Looking at the stack trace, the exception is thrown in CANL when called by the SSLEngine. This follows the contract specified by the JDK, see https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/X509TrustManager.html#checkClientTrusted-java.security.cert.X509Certificate:A-java.lang.String-

This is apparently propagated by the SSLEngine since SSLEngine#unwrap throws an exception. It would be the job of the SSLEngine to generate an alert frame. I am not certain how the caller (Jetty) could react in any different way than to cut the connection.

The error is logged in Jetty in HttpConnection#fillRequestBuffer:

            catch (IOException e)
            {
                LOG.debug(e);
                return -1;
            }

I can write an aspect to intercept this and add some logging at warn for particular errors. Since the exception is however a generic CertificateException, I cannot be particularly specific about which types of errors are logged. Although CANL is quite specific in categorizing the error and generate a decent error message, SSLTrustManager uncritically throws CertificateException for any error.

**Comment by gbehrmann** [comment] 2015-10-18 14:51
I read through the JavaDoc and although it isn't particularly clear on what is supposed to happen in this case, some of the description may sound as if one should call methods to close the inbound and outbound streams and then keep calling wrap/unwrap to let the engine shut down properly. Jetty doesn't do that - if the handshake fails with an exception it closes the socket. Given how unclear the JavaDoc is on the point, it would make a very weak bug report.

**Comment by gbehrmann** [comment] 2015-10-19 07:54
I found a better approach than aspects: CANL supports listeners for various events, including validation errors. I am working on a patch.

**Comment by gbehrmann** [comment] 2015-10-19 09:28
See https://rb.dcache.org/r/8674/

**Comment by gbehrmann** [comment] 2015-11-22 11:14
Fixed by ee5946138fca73f7a893a2c979e589f382cae5f9

**Closed by gbehrmann** 2015-11-22 11:14 UTC
Labels: bug
