### ISSUE TITLE
Xroot: successful write but copy still fails with "no such file"

### ISSUE THREAD

**Issue by chaen** [dCache/dcache#5882] opened 2021-04-30 13:45 UTC
Hi,

LHCb observes a strange behavior. Occasionally, a direct transfer from a worker node to the storage with xroot fails with an error like

```
Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded with an error: [3011] No such file or directory /pnfs/gridka.de/lhcb/LHCb-Disk/lhcb/buffer/lhcb/MC/2017/SIM/00133306/0000/00133306_00008388_1.sim
```

DIRAC immediately retries the transfer with https, and that works fine. 
However, what is very puzzling is that from the dCache point of view, the xroot write call succeeds. 

The reason I am opening the ticket against dCache and not gfal2 or xroot is that we see it happening only against dCache sites. 

What we observe is the following:
* it seems to happen only for small files (< 25 kB).
* I have a very hard time to reproduce it from lxplus, but Samuel at Gridka manages to reproduce it systematically from gridka worker node (good hint for a race condition)

Here is a script to reproduce it:

```python

#!/usr/bin/env python

import os
import gfal2
import random
import logging

logging.basicConfig(level=logging.DEBUG)
LOOP=3000
FILESIZE=5000
FILENAME = os.path.realpath('tiny.txt')
BASE_URL = "root://lhcbxrootd-kit.gridka.de//pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/dCacheTiny"

for i in range(LOOP):
  print "LOOP %s"%i
  with open('tiny.txt','wt') as f:
    r = os.urandom(FILESIZE)
    f.write(r)
  ctx = gfal2.creat_context()
  params = ctx.transfer_parameters()
  params.overwrite = True
  params.set_checksum(gfal2.checksum_mode.both, 'ADLER32', '')
  rndFolder = random.randint(1, 999999*LOOP)
  ctx.filecopy(params, 'file://' + FILENAME , "%s/%s/tiny.txt"%(BASE_URL, rndFolder))
```

Here is an extract from the debug log of root:

```
[2021-04-30 15:27:49.187852 +0200][Debug  ][PostMaster        ] Creating new channel to: root://lhcbxrootd-kit.gridka.de:1094?xrd.gsiusrpxy=/home/dcache-mon/dcache-mon.proxy
[2021-04-30 15:27:49.187897 +0200][Debug  ][PostMaster        ] [lhcbxrootd-kit.gridka.de:1094] Stream parameters: Network Stack: IPAuto, Connection Window: 120, ConnectionRetry: 5, Stream Error Window: 1800
[2021-04-30 15:27:49.187928 +0200][Debug  ][TaskMgr           ] Registering task: "TickGeneratorTask for: root://lhcbxrootd-kit.gridka.de:1094?xrd.gsiusrpxy=/home/dcache-mon/dcache-mon.proxy" to be run at: [2021-04-30 15:28:04 +0200]
[2021-04-30 15:27:49.187950 +0200][Dump   ][PostMaster        ] [lhcbxrootd-kit.gridka.de:1094] Sending message kXR_rm (path: //pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/dCacheTiny/1451167154/tiny.txt?xrd.gsiusrpxy=/home/dcache-mon/dcache-mon.proxy) (0xc3e400) through substream 0 expecting answer at 0
[2021-04-30 15:27:49.188820 +0200][Debug  ][PostMaster        ] [lhcbxrootd-kit.gridka.de:1094] Found 4 address(es): [::ffff:192.108.47.157]:1094, [::ffff:192.108.47.145]:1094, [2a00:139c:5:1d9:0:41:d2:b4]:1094, [2a00:139c:5:1d9:0:41:d2:c0]:1094
[2021-04-30 15:27:49.188874 +0200][Debug  ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Attempting connection to [2a00:139c:5:1d9:0:41:d2:c0]:1094
[2021-04-30 15:27:49.188916 +0200][Debug  ][Poller            ] Adding socket 0xc495e0 to the poller
[2021-04-30 15:27:49.189246 +0200][Debug  ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Async connection call returned
[2021-04-30 15:27:49.189285 +0200][Debug  ][XRootDTransport   ] [lhcbxrootd-kit.gridka.de:1094.0] Sending out the initial hand shake + kXR_protocol
[2021-04-30 15:27:49.189335 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Wrote a message:  (0xa8005580), 44 bytes
[2021-04-30 15:27:49.189708 +0200][Dump   ][XRootDTransport   ] [msg: 0xa8005580] Expecting 8 bytes of message body
[2021-04-30 15:27:49.189736 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Received message header, size: 8
[2021-04-30 15:27:49.189780 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Received a message of 16 bytes
[2021-04-30 15:27:49.189799 +0200][Debug  ][XRootDTransport   ] [lhcbxrootd-kit.gridka.de:1094.0] Got the server hand shake response (type: manager [], protocol version 400)
[2021-04-30 15:27:49.189826 +0200][Dump   ][XRootDTransport   ] [msg: 0xa8005580] Expecting 8 bytes of message body
[2021-04-30 15:27:49.189842 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Received message header, size: 8
[2021-04-30 15:27:49.189859 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Received a message of 16 bytes
[2021-04-30 15:27:49.189876 +0200][Debug  ][XRootDTransport   ] [lhcbxrootd-kit.gridka.de:1094.0] kXR_protocol successful (type: server [], protocol version 400)
[2021-04-30 15:27:49.190572 +0200][Debug  ][XRootDTransport   ] [lhcbxrootd-kit.gridka.de:1094.0] Sending out kXR_login request, username: dcache-m, cgi: ?xrd.cc=de&xrd.tz=1&xrd.appname=python2.7&xrd.info=&xrd.hostname=gm-2-kit-e.gridka.de&xrd.rn=v5.1.1, dual-stack: true, private IPv4: false, private IPv6: false
[2021-04-30 15:27:49.190627 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Wrote a message:  (0xa80031c0), 123 bytes
[2021-04-30 15:27:49.190989 +0200][Dump   ][XRootDTransport   ] [msg: 0xa80031c0] Expecting 49 bytes of message body
[2021-04-30 15:27:49.191017 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Received message header, size: 8
[2021-04-30 15:27:49.191041 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Received a message of 57 bytes
[2021-04-30 15:27:49.191062 +0200][Debug  ][XRootDTransport   ] [lhcbxrootd-kit.gridka.de:1094.0] Logged in, session: 5c85cfca04b14f52b81eaf344621216d
[2021-04-30 15:27:49.191076 +0200][Debug  ][XRootDTransport   ] [lhcbxrootd-kit.gridka.de:1094.0] Authentication is required: &P=gsi,v:10400,c:ssl,ca:dd4b34ea
[2021-04-30 15:27:49.191090 +0200][Debug  ][XRootDTransport   ] [lhcbxrootd-kit.gridka.de:1094.0] Sending authentication data
[2021-04-30 15:27:49.191145 +0200][Debug  ][XRootDTransport   ] [lhcbxrootd-kit.gridka.de:1094.0] Trying to authenticate using gsi
[2021-04-30 15:27:49.206410 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Wrote a message:  (0xa8000ec0), 136 bytes
[2021-04-30 15:27:49.212930 +0200][Dump   ][XRootDTransport   ] [msg: 0xa8101180] Expecting 2679 bytes of message body
[2021-04-30 15:27:49.212965 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Received message header, size: 8
[2021-04-30 15:27:49.212988 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Received a message of 2687 bytes
[2021-04-30 15:27:49.213006 +0200][Debug  ][XRootDTransport   ] [lhcbxrootd-kit.gridka.de:1094.0] Sending more authentication data for gsi
[2021-04-30 15:27:49.230340 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Wrote a message:  (0xa810acd0), 7612 bytes
[2021-04-30 15:27:49.243181 +0200][Dump   ][XRootDTransport   ] [msg: 0xa810acd0] Expecting 0 bytes of message body
[2021-04-30 15:27:49.243261 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Received message header, size: 8
[2021-04-30 15:27:49.243279 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Received a message of 8 bytes
[2021-04-30 15:27:49.243372 +0200][Debug  ][XRootDTransport   ] [lhcbxrootd-kit.gridka.de:1094.0] Authenticated with gsi.
[2021-04-30 15:27:49.243405 +0200][Debug  ][PostMaster        ] [lhcbxrootd-kit.gridka.de:1094] Stream 0 connected.
[2021-04-30 15:27:49.243449 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Wrote a message: kXR_rm (path: //pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/dCacheTiny/1451167154/tiny.txt?xrd.gsiusrpxy=/home/dcache-mon/dcache-mon.proxy) (0xc3e400), 152 bytes
[2021-04-30 15:27:49.243489 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Successfully sent message: kXR_rm (path: //pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/dCacheTiny/1451167154/tiny.txt?xrd.gsiusrpxy=/home/dcache-mon/dcache-mon.proxy) (0xc3e400).
[2021-04-30 15:27:49.243509 +0200][Dump   ][XRootD            ] [lhcbxrootd-kit.gridka.de:1094] Message kXR_rm (path: //pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/dCacheTiny/1451167154/tiny.txt?xrd.gsiusrpxy=/home/dcache-mon/dcache-mon.proxy) has been successfully sent.
[2021-04-30 15:27:49.243524 +0200][Debug  ][ExDbgMsg          ] [lhcbxrootd-kit.gridka.de:1094] Moving MsgHandler: 0xbff7d0 (message: kXR_rm (path: //pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/dCacheTiny/1451167154/tiny.txt?xrd.gsiusrpxy=/home/dcache-mon/dcache-mon.proxy) ) from out-queu to in-queue.
[2021-04-30 15:27:49.243552 +0200][Dump   ][PostMaster        ] [lhcbxrootd-kit.gridka.de:1094.0] All messages consumed, disable uplink
[2021-04-30 15:27:49.253364 +0200][Dump   ][XRootDTransport   ] [msg: 0xa8000d00] Expecting 0 bytes of message body
[2021-04-30 15:27:49.253457 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Received message header for 0xa8000d00 size: 8
[2021-04-30 15:27:49.253481 +0200][Dump   ][AsyncSock         ] [lhcbxrootd-kit.gridka.de:1094.0] Received message 0xa8000d00 of 8 bytes
[2021-04-30 15:27:49.253499 +0200][Dump   ][PostMaster        ] [lhcbxrootd-kit.gridka.de:1094] Handling received message: 0xa8000d00.
[2021-04-30 15:27:49.253570 +0200][Dump   ][XRootD            ] [lhcbxrootd-kit.gridka.de:1094] Got a kXR_ok response to request kXR_rm (path: //pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/dCacheTiny/1451167154/tiny.txt?xrd.gsiusrpxy=/home/dcache-mon/dcache-mon.proxy)
[2021-04-30 15:27:49.253614 +0200][Debug  ][ExDbgMsg          ] [lhcbxrootd-kit.gridka.de:1094] Calling MsgHandler: 0xbff7d0 (message: kXR_rm (path: //pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/dCacheTiny/1451167154/tiny.txt?xrd.gsiusrpxy=/home/dcache-mon/dcache-mon.proxy) ) with status: [SUCCESS] .
[2021-04-30 15:27:49.253636 +0200][Dump   ][FileSystem        ] [0xbe4090@lhcbxrootd-kit.gridka.de:1094] Assigning lhcbxrootd-kit.gridka.de:1094 as last URL
[2021-04-30 15:27:49.253679 +0200][Debug  ][ExDbgMsg          ] [lhcbxrootd-kit.gridka.de:1094] Destroying MsgHandler: 0xbff7d0.
INFO:gfal2:Destination file removed
Traceback (most recent call last):
  File "test-checksum.py", line 24, in <module>
    ctx.filecopy(params, 'file://' + FILENAME , "%s/%s/tiny.txt"%(BASE_URL, rndFolder))
gfal2.GError: Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded with an error: [3011] No such file or directory /pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/dCacheTiny/1451167154/tiny.txt Got an error while querying the checksum! (destination)
```

Samuel has kindly agreed to provide any log you may deem useful 

Does that ring any bell ? 
Thanks a lot
Chris

**Comment by alrossi** [comment] 2021-05-03 14:58
H Chris,

sorry for the delay here.  I will be investigating this soon.


Al

**Comment by alrossi** [comment] 2021-05-04 15:56
Update.  I have reproduced your error with the script you provided.  Now I am trying to understand it.   

What I see in the door is that the checksum query fails to find the file and then delete is called. 

```
04 May 2021 10:48:59 (xrootd-1095-fndcatemp2) [door:xrootd-1095-fndcatemp2@xrootd-1095-fndcatemp2Domain:AAXBgwQv3yA] [id: 0xb351c136, L:/131.225.240.93:1095 - R:/131.225.240.89:56766] FLUSH
04 May 2021 10:48:59 (xrootd-1095-fndcatemp2) [door:xrootd-1095-fndcatemp2@xrootd-1095-fndcatemp2Domain:AAXBgwQv3yA] [id: 0xb351c136, L:/131.225.240.93:1095 - R:/131.225.240.89:56766] READ: query[3,0,//pnfs/fs/usr/test/arossi/volatile/671041427?cks.type=adler32]
04 May 2021 10:48:59 (xrootd-1095-fndcatemp2) [door:xrootd-1095-fndcatemp2@xrootd-1095-fndcatemp2Domain:AAXBgwQv3yA] [id: 0xb351c136, L:/131.225.240.93:1095 - R:/131.225.240.89:56766] READ COMPLETE
04 May 2021 10:48:59 (xrootd-1095-fndcatemp2) [door:xrootd-1095-fndcatemp2@xrootd-1095-fndcatemp2Domain:AAXBgwQv3yA] Xrootd-Error-Response: ErrorNr=3011 ErrorMsg=No such file or directory /pnfs/fs/usr/test/arossi/volatile/671041427
04 May 2021 10:48:59 (xrootd-1095-fndcatemp2) [door:xrootd-1095-fndcatemp2@xrootd-1095-fndcatemp2Domain:AAXBgwQv3yA] [id: 0xb351c136, L:/131.225.240.93:1095 - R:/131.225.240.89:56766] WRITE: error[3011,No such file or directory /pnfs/fs/usr/test/arossi/volatile/671041427]
04 May 2021 10:48:59 (xrootd-1095-fndcatemp2) [door:xrootd-1095-fndcatemp2@xrootd-1095-fndcatemp2Domain:AAXBgwQv3yA] [id: 0xb351c136, L:/131.225.240.93:1095 - R:/131.225.240.89:56766] FLUSH
04 May 2021 10:48:59 (xrootd-1095-fndcatemp2) [door:xrootd-1095-fndcatemp2@xrootd-1095-fndcatemp2Domain:AAXBgwQv3yA] [id: 0xb351c136, L:/131.225.240.93:1095 - R:/131.225.240.89:56766] READ: rm[//pnfs/fs/usr/test/arossi/volatile/671041427,xrd.gsiusrpxy=/tmp/x509up_u8773]
04 May 2021 10:48:59 (xrootd-1095-fndcatemp2) [door:xrootd-1095-fndcatemp2@xrootd-1095-fndcatemp2Domain:AAXBgwQv3yA] [id: 0xb351c136, L:/131.225.240.93:1095 - R:/131.225.240.89:56766] READ COMPLETE
04 May 2021 10:48:59 (xrootd-1095-fndcatemp2) [door:xrootd-1095-fndcatemp2@xrootd-1095-fndcatemp2Domain:AAXBgwQv3yA] Trying to delete //pnfs/fs/usr/test/arossi/volatile/671041427
```

Investigating this.

**Comment by alrossi** [comment] 2021-05-04 16:14
Just to be precise, let me ask you here:

what version of dCache is this?
what version of the xrdcp client?

Thanks.

**Comment by alrossi** [comment] 2021-05-04 17:19
this seems to be a race between the pool and the PnfsManager.  Because the file is small, it gets written very quickly and the client then moves on to request the checksum before the namespace has been updated.   I have confirmed this because putting a short wait in the checksum call on the door seems to solve the issue.

I am studying what the best fix for this is.

**Comment by paulmillar** [comment] 2021-05-04 18:18
Just as some (hopefully helpful) info: the checksum information should be written to the namespace (via PnfsManager) in `WriteHandlerImpl#registerFileAttributesInNameSpace`.  This happens when the upload completes (independently of which protocol is used).  The pool sends the message to PnfsManager and waits for a reply: it's synchronous.  This happens in `ReplicaDescriptor#commit`, which is called from within `DefaultPostTransferService`.

All this happens as a consequence of calling `Mover#close`, which should be triggered by the client's `kXR_close` request.  If I've understood correctly, the pool's `kXR_ok` _should_ only be sent after the mover has been closed successfully, which implies any checksum has been sent to PnfsManager, and the pool has waited for the reply.

So, _theoretically_ the pool should have guaranteed to have written the checksum before replying `kXR_ok` to the client.

Just as a "shot in the dark" ... are we sure the client is waiting for the `kXR_ok` response from the pool before querying the file's checksum?

**Comment by alrossi** [comment] 2021-05-04 19:01
It would be useful to me to know how to get the xrdcp debug output when running gfal.   

Doing 
```
xrdcp -C adler32 tint.txt <destination>   
```
does provoke same issue.

Does gfal do -C in xrdcp, or does it use xrdfs to query?   I need to see this logging for me to be able to address what @paulmillar has stated above (which I believe he is correct about).

**Comment by alrossi** [comment] 2021-05-04 19:15
This is the sequence with the normal xrdcp client

```
[2021-05-04 13:57:39.954604 -0500][Dump   ][XRootD            ] [fndcatemp2.fnal.gov:33126] Got a kXR_ok response to request kXR_close (handle: 0x00000000)
[2021-05-04 13:57:39.954658 -0500][Debug  ][ExDbgMsg          ] [fndcatemp2.fnal.gov:33126] Calling MsgHandler: 0x25eb6b0 (message: kXR_close (handle: 0x00000000) ) with status: [SUCCESS] .
...
[2021-05-04 13:57:39.954780 -0500][Debug  ][Utility           ] Attempting checksum calculation, mode: end2end.
[2021-05-04 13:57:39.954868 -0500][Dump   ][Utility           ] Checksum for source is: adler32:a510a34e
...
[2021-05-04 13:57:39.955224 -0500][Dump   ][FileSystem        ] [0x25eb760@fndcatemp2.fnal.gov:33126] Sending kXR_query (code: kXR_Qcksum, arg length: 85)
```

What I need to see is if this is true inside gfal as well.

**Comment by paulmillar** [comment] 2021-05-04 20:05
I think what I'd do is update the pool code to print a log statement just before `WriteHandleImpl` sends PnfsManager the update message (verifying that the message does, indeed, include the file's checksum) and another log statement just before the client responds `kXR_ok` to the client.  I would then run the test-case that demonstrates the problem and check what the pool log file says.

That should  give a clear indication whether the pool is updating the namespace (including the checksum information) before replying `kXR_ok`.

**Comment by chaen** [comment] 2021-05-05 07:30
Thanks for having a look at this guys. I'm glad you could reproduce. 
As far as I know, gfal delegates everything to xroot library. I'll forward the link to this ticket to the gfal guru. 

Funnily enough though, before reproducing the problem with the script I added in the issue, I managed (or rather Samuel :-) ) to reproduce it with `gfal-copy` cli, and not the python binding. And it turns out that the error was checksum related. I did not believe it because I was tricked in the past by what gfal cli does internally (like `stat` before creating or that kind of things, which may report different errors).

**Comment by mpatrascoiu** [comment] 2021-05-05 07:56
Hello,

I'm also interested to know the xrootd client version.

When using TPC (as is the case here), Gfal2 will delegate the checksum work to the underlying XRrootd TPC job.
The following log messages should show up in the Gfal2 logs:
```
Predefined Checksum Type: <type>
Predefined Checksum Value: <value>
```

To get XRootD logs when using Gfal2, you need to put Gfal2 in debug mode + set the `XRD_LOGLEVEL=Debug` environment variable.

(In the past there was this ticket: https://github.com/xrootd/xrootd/issues/1359. Do you think it has anything to do with it? It does not look like it but still worth bringing it up)

**Comment by chaen** [comment] 2021-05-05 08:00
Sorry I overlooked the version question. We have xroot `v4.11.2` 
As for dCache, I'll ask Samuel (unless @paulmillar knows by heart what Gridka is running :-) )

@mpatrascoiu why would it be TPC ? we copy a local file to the remote storage.

**Comment by mpatrascoiu** [comment] 2021-05-05 08:12
@chaen here we're just playing around with terminology

The Gfal2 Xrootd plugin is TPC-only. 

Gfal2 will delegate a TPC job to this plugin if `<src>` is one of `root:// OR file://` and `<dst>` is one of `root:// OR file://` (unless `<src>` = `<dst>` = `file://`). Behind the scene, `file:// --> root://` transfer is not _third party copy_ but the XRootd client is smart enough to handle this case.

If the `root://` protocol is involved but Gfal2 can't delegate to the XRootd plugin, we enter what is (perhaps improperly) called `streaming` copy. (e.g.: `root://` --> `davs://`).

**Comment by paulmillar** [comment] 2021-05-05 09:03
Sorry, I'm don't so up-to-date with KIT's deployments :-/

**Comment by samuambroj** [comment] 2021-05-05 09:11
I saw the comments just now. We are running dCache 5.2.31 at KIT on all dCache services, but the doors and headnodes, where 5.2.35 is running.

**Comment by alrossi** [comment] 2021-05-05 12:26
Hi all,

thanks for all a the feedback.  I spent some time with this yesterday trying to see if there was any sign of a timing issue in dCache (door vs pool) by adding some logging statements as @paulmillar suggested.  Comparing the gfal script, which fails, to the simple xrootd equivalent.  But so far I have not uncovered anything revealing.  

As far as  xrootd/xrootd#1359, I don't believe that is relevant because (a) it involves the 5+ client, and you are using 4.11, and (b) it only happens on real TPC, where what is happening inside the xroot client here, whatever it looks like to gfal, is not TPC.

I will try to obtain the xrootd logs from gfal and see if that shows me anything useful.

I am not sure exactly what "delegating the checksum work to the underlying XRrootd job" actually means:

xrdcp -C adler32 .... 

or

xrdcp ...
xrdfs query

From the dCache log timing, it looks like it is probably the former, but I just wanted to check.

I'll post further results as they come.

**Comment by alrossi** [comment] 2021-05-05 13:37
The log output from gfal does not significantly differ from the straight xroot log.  In particular, the client waits for the SUCCESS of the close of the file on the pool before issuing the checksum request, which is redirected to the door.

**Comment by alrossi** [comment] 2021-05-05 14:21
What does this mean (in the gfal script)?

```
params.set_checksum(gfal2.checksum_mode.both, 'ADLER32', '')
```

in particular, what is the empty string parameter?

**Comment by mpatrascoiu** [comment] 2021-05-05 14:36
Hello @alrossi ,

I can answer some of the questions:
1. Meaning of _delegating the checksum work to the underlying XRootd job_ 
Gfal2 creates an `XrdCl::Job` where it sets the checksum mode, type and value. It resembles the `xrdcp -C` behavior.
2. The signature of `params.set_checksum(..)` is 
```cpp
void GfaltParams::set_checksum(gfalt_checksum_mode_t mode, const std::string &type, const std::string &value)
```
The _value_ may be empty if the mode makes sense (such as _both_).

**Comment by alrossi** [comment] 2021-05-05 16:36
I think I understand where the race is coming from now.   I need to confirm this by doing one last test.  But, in brief, it has to do with the combination of GFAL sending a kXR_posc directive on open and the re-use of the same connection to request the checksum.   Doing a straight xrdcp -C does not include the former, and it reconnects, going through protocol handshakes again before sending the checksum query.   

This is obviously a dCache issue which needs to be fixed.

**Comment by alrossi** [comment] 2021-05-05 17:11
It is definitely the combination.  With xrdcp I cannot reproduce this doing:
```
for i in `seq 1 300`; do  xrdcp5x -P -C adler32 tiny.txt xroot://fndcatemp2.fnal.gov:1095//pnfs/fs/usr/test/arossi/volatile/data-${i}-`date | tr ' ' '.'`; done
```

whereas the python gfal script fails consistently on the first iteration.

So the reconnect and authentication before the checksum allows enough time for the persist-on-close transaction to complete.

Now I have to figure out how best to fix this.

**Comment by alrossi** [comment] 2021-05-05 20:32
https://rb.dcache.org/r/13021/

**Comment by alrossi** [comment] 2021-05-06 19:01
https://rb.dcache.org/r/13023/

**Comment by alrossi** [comment] 2021-05-06 19:01
Replaced original patch with a superior solution

**Comment by alrossi** [comment] 2021-05-20 13:33
The fix for master is still under review, but the stable branches now have a patch which should be applied in the next release.

**Comment by chaen** [comment] 2021-12-20 15:49
Hi ! From the ticket, it is unclear to me whether the fix is merged or not. Gridka is running 6.2.34, and I believe we are still observing that behavior. 
Samuel has ran the test script again, and could reproduce it. He stopped the second attempt after 1248 successful copies :-) 

```
LOOP 3
INFO:gfal2:[gfal_module_load] plugin 
/usr/lib64/gfal2-plugins//libgfal_plugin_srm.so loaded with success
INFO:gfal2:[gfal_module_load] plugin 
/usr/lib64/gfal2-plugins//libgfal_plugin_dcap.so loaded with success
INFO:gfal2:[gfal_module_load] plugin 
/usr/lib64/gfal2-plugins//libgfal_plugin_xrootd.so loaded with success
INFO:gfal2:[gfal_module_load] plugin 
/usr/lib64/gfal2-plugins//libgfal_plugin_gridftp.so loaded with success
INFO:gfal2:[gfal_module_load] plugin 
/usr/lib64/gfal2-plugins//libgfal_plugin_http.so loaded with success
INFO:gfal2:[gfal_module_load] plugin 
/usr/lib64/gfal2-plugins//libgfal_plugin_file.so loaded with success
INFO:gfal2:Event triggered: BOTH GFAL2:CORE:COPY LIST:ENTER
INFO:gfal2:Event triggered: BOTH GFAL2:CORE:COPY LIST:ITEM 
file:///home/dcache-mon/tiny.txt => 
root://lhcbxrootd-kit.gridka.de//pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/dCacheTiny/895848856/tiny.txt
INFO:gfal2:Event triggered: BOTH GFAL2:CORE:COPY LIST:EXIT
INFO:gfal2:Event triggered: BOTH xroot TRANSFER:ENTER 
file://localhost///home/dcache-mon/tiny.txt?xrd.gsiusrpxy=/home/dcache-mon/dcache-mon.proxy&xrdcl.intent=tpc 
=> 
root://lhcbxrootd-kit.gridka.de:1094///pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/dCacheTiny/895848856/tiny.txt?xrd.gsiusrpxy=/home/dcache-mon/dcache-mon.proxy&xrdcl.intent=tpc
INFO:gfal2:Event triggered: BOTH xroot TRANSFER:TYPE streamed
INFO:gfal2:Event triggered: BOTH xroot TRANSFER:EXIT Job finished, [ERROR] 
Server responded with an error: [3011] No such file or directory 
/pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/dCacheTiny/895848856/tiny.txt 
Got an error while querying the checksum! (destination)

INFO:gfal2:Destination file removed
Traceback (most recent call last):
  File "test-checksum.py", line 24, in <module>
    ctx.filecopy(params, 'file://' + FILENAME , "%s/%s/tiny.txt"%(BASE_URL, 
rndFolder))
gfal2.GError: Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded 
with an error: [3011] No such file or directory 
/pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/dCacheTiny/895848856/tiny.txt 
Got an error while querying the checksum! (destination)

```

**Comment by alrossi** [comment] 2022-06-08 14:59
the issue was fixed; I believe the user just needed to get the updated rpm.

**Closed by alrossi** 2022-06-08 14:59 UTC
Labels: xroot
