### ISSUE TITLE
Open srr api to external access

### ISSUE THREAD

**Issue by XMol** [dCache/dcache#6181] opened 2021-10-26 11:35 UTC
Hello dCache.org,

as became obvious by the feedback on the user-forum thread "The new SRR module is GA", multiple sites would like you to lift the restriction on the [new SRR REST-API](https://github.com/dcache/dcache/commit/24d79fdd765c568ac4fc3ceabce502d997eb7379) such that it may be queried from other places besides localhost.

The benefits are quite obvious (to me):
* Consumers - most prominently WLCG's CRIC - may retrieve up-to-date information any time it wants to.
* Site admins are no longer obligated to set up a cronjob that downloads the report and then upload it to a location where consumers may read it from.

Thank you for all your effort that went into this service so far!

Best regards,
Xavier.

**Comment by XMol** [comment] 2021-12-14 10:34
Hello dCache.org,

are there other open issues regarding SRR that you have to work on in parallel? If not, may I ask you kindly to include the necessary changes in one of the upcoming releases soon? According to Tigran, actually very little work would go into it, so I'm surprised this request is pending for so long, despite the feedback on the user-forum.

Best regards,
Xavier.

**Comment by paulmillar** [comment] 2021-12-14 11:08
Hi Xavier,

The changes in behaviour you describe are available with dCache v7.2.6, v7.1.16, v7.0.25, v6.2.36.

These dCache versions were released on 2021-12-10 (last Friday).

Cheers,
Paul.

**Comment by kofemann** [comment] 2021-12-14 11:12
@paulmillar The direrd change is not in the dcache code base and still in RB: https://rb.dcache.org/r/13273/

**Comment by XMol** [comment] 2021-12-14 11:52
Thank you for the quick update!

**Comment by XMol** [comment] 2022-02-23 14:05
Hello @kofemann, @paulmillar,

again two months have passed and the issue in RB that Tigran linked has seen no updates either. I trust you did not forget about this request? 😉 

Ciao,  
Xavier.

**Comment by paulmillar** [comment] 2022-02-23 16:49
I believe this is done (or almost done).  You should see something "soon".

**Comment by XMol** [comment] 2022-02-25 09:53
Thank you @kofemann,

adding a new property to toggle the behavior is fine for me/us.

Ciao,  
Xavier.

**Comment by ageorget** [comment] 2022-03-15 12:42
Hi,
I'm trying to enable public access to SRR with the 6.2.41 dCache version but I still got 403 forbidden error if I ask anything else than localhost.
My Frontend configuration looks like : 

```
[FrontendDomain]
[FrontendDomain/frontend]
frontend.authn.basic=true
frontend.authn.protocol=https
frontend.authz.anonymous-operations=READONLY
frontend.srr.public=true
```
Same result switching to http, or anonymous-operation=FULL
On the Frontend host : 
```
curl http://localhost:3880/api/v1/srr
{
  "storageservice" : {
    "name" : "",
    "id" : "ccsrm.in2p3.fr",
    "servicetype" : "multidisk",
    "implementation" : "dCache",
    "implementationversion" : "6.2.41",
...

curl http://ccdcamcli06.in2p3.fr:3880/api/v1/srr           
{"errors":[{"message":"Forbidden","status":"403"}]}


level=INFO ts=2022-03-15T13:21:30.552+0100 event=org.dcache.frontend.request request.method=GET request.url=https://localhost:3880/api/v1/srr response.code=200 response.reason=OK socket.remote=[::1]:43508 user-agent=curl/7.29.0 user.mapped=nobody response.entity="{\n  \"storageservice\" : {\n    \"name\"[...]"
level=WARN ts=2022-03-15T13:27:40.848+0100 event=org.dcache.frontend.request request.method=GET request.url=https://ccdcamcli06.in2p3.fr:3880/api/v1/srr response.code=403 response.reason=Forbidden socket.remote=[2001:660:5009:1:134:158:109:246]:48174 user-agent=curl/7.29.0 user.mapped=nobody response.entity="{\"errors\":[{\"message\":\"Forbidden\",\"[...]"

```
Am I missing something?
Adrien

**Comment by lemora** [comment] 2022-03-17 10:32
Hi Adrien,

sorry for the trouble; the problem is identified and a fix is on the way. Hopefully it will be included in the next bugfix releases.

Lea

**Closed** 2022-03-17 10:35 UTC
Labels: enhancement

**Comment by ageorget** [comment] 2022-03-17 16:02
Hi Lea, 
Thanks for the quick fix, indeed it's working with `frontend.srr.public=false` :)

Adrien
