### ISSUE TITLE
Apparent message bounce observed on sisyphus

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#2001] opened 2015-12-01 14:58 UTC
Today, sisyphus failed due to /var partition becoming full; the partition that (on this machine) also holds the PostgreSQL instance.

The partition was full because the `dCacheDomain.events` file was 2.7 GiB in size.  Previous builds have recorded this file with sizes between 30 MiB and 70 MiB.

In this case, the file showed entries with many, many messages to PnfsManager, looking like a NoRouteToCellException.

The following is taken from near the end of the log file.  The original entry was a single line; line-breaks have been added to aid readability:

```
ts=2015-12-01T12:57:23.245+0100
    event=org.dcache.cells.deliver.begin
    uoid=<1448970572233:1918888>
    lastuoid=<1448970572232:1918886>
    session=xQY:47:srm1:put:-2147482617:-2147482616
    message=NoRouteToCellException
    source=[>PnfsManager@dCacheDomain:PnfsManager@dCacheDomain:SRM-sisyphus@dCacheDomain:
        [59 REPETITIONS]
        :SRM-sisyphus@dCacheDomain]
    destination=[SRM-sisyphus@dCacheDomain:
        [144 REPETITIONS]
        :SRM-sisyphus@dCacheDomain:>SRM-sisyphus@dCacheDomain:
        [156 REPETITIONS]
        :SRM-sisyphus@dCacheDomain]
```
The phrase `[n REPETITIONS]` replaces an n item colon-separated list of the phrase `SRM-sisyphus@dCacheDomain`.

**Comment by paulmillar** [comment] 2015-12-01 15:10
Likely caused by: https://rb.dcache.org/r/8783/
Commit 8282ec

**Comment by paulmillar** [comment] 2015-12-01 15:48
Jenkins build that exhibited the problem: https://ci.dcache.org/job/dCache-master/6637/

**Comment by gbehrmann** [comment] 2015-12-02 10:49
Yeah, I newer doubted that 8282ec is the cause (it's pretty obvious that if you have a problem with bouncing no route to cell exceptions and there was a patch that changed how we detect bouncing no route to cell exceptions, that this patch is likely the cause).

Could I get a copy of the events log, or at least a larger part of it? I am interested in the part from the last restart to a little after the problem started.

**Comment by gbehrmann** [comment] 2015-12-02 11:20
I would also like a copy of the domain log files involved.

**Comment by gbehrmann** [comment] 2016-02-11 09:08
https://rb.dcache.org/r/8783/ updated with a possible fix.

**Comment by jstarek** [comment] 2016-08-25 14:04
Can we close this ticket? It seems the fix worked.

**Closed** 2016-08-26 06:23 UTC
Labels: bug
