### ISSUE TITLE
cannot overwrite directory tags using NFS dot commands

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#1671] opened 2015-06-17 14:07 UTC
master, 2cda82dbf78b1b10ed5672254aa8e68bb9af97a6

    [root@otfrid ~]# mkdir -p /pnfs/fs/usr/test/arossi
    [root@otfrid ~]# cd /pnfs/fs/usr/test/arossi
    [root@otfrid arossi]# echo "NEARLINE" > ".(tag)(AccessLatency)"
    [root@otfrid arossi]# cat ".(tag)(AccessLatency)"
    NEARLINE
    [root@otfrid arossi]# mkdir online
    [root@otfrid arossi]# cd online
    [root@otfrid online]# echo "ONLINE" > ".(tag)(AccessLatency)"
    bash: .(tag)(AccessLatency): Remote I/O error
    
    The reported error:
    17 Jun 2015 08:04:45 (NFS-fndcatemp2) [] Unhandled exception:
    org.dcache.chimera.IOHimeraFsException: ERROR: duplicate key value violates unique constraint "t_tags_pkey"
    Detail: Key (ipnfsid, itagname)=(000015CD7F81D3604BB68B680A28CB98006C, AccessLatency) already exists.
        at org.dcache.chimera.JdbcFs.createTag(JdbcFs.java:1752) ~[chimera-2.14.0-SNAPSHOT.jar:2.14.0-SNAPSHOT]
        at org.dcache.chimera.JdbcFs.createFile(JdbcFs.java:326) ~[chimera-2.14.0-SNAPSHOT.jar:2.14.0-SNAPSHOT]
        at org.dcache.nfs.vfs.ChimeraVfs.create(ChimeraVfs.java:97) ~[nfs4j-core-0.10.4.jar:0.10.4]
        at org.dcache.nfs.vfs.VfsCache.create(VfsCache.java:155) ~[nfs4j-core-0.10.4.jar:0.10.4]
        at org.dcache.nfs.vfs.PseudoFs.create(PseudoFs.java:152) ~[nfs4j-core-0.10.4.jar:0.10.4]
        at org.dcache.nfs.v4.OperationOPEN.process(OperationOPEN.java:161) ~[nfs4j-core-0.10.4.jar:0.10.4]
        at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:149) ~[nfs4j-core-0.10.4.jar:0.10.4]
        at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48) [nfs4j-core-0.10.4.jar:0.10.4]
        at org.dcache.xdr.RpcDispatcher$1.run(RpcDispatcher.java:85) [oncrpc4j-core-2.3.3.jar:na]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) [grizzly-framework-2.3.21.jar:2.3.21]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) [grizzly-framework-2.3.21.jar:2.3.21]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
    Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "t_tags_pkey"
       Detail: Key (ipnfsid, itagname)=(000015CD7F81D3604BB68B680A28CB98006C, AccessLatency) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
        at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61) ~[HikariCP-2.3.7.jar:na]
        at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java) ~[HikariCP-2.3.7.jar:na]
        at org.dcache.chimera.FsSqlDriver.assignTagToDir(FsSqlDriver.java:1553) ~[chimera-2.14.0-SNAPSHOT.jar:2.14.0-SNAPSHOT]
        at org.dcache.chimera.FsSqlDriver.createTag(FsSqlDriver.java:1444) ~[chimera-2.14.0-SNAPSHOT.jar:2.14.0-SNAPSHOT]
        at org.dcache.chimera.JdbcFs.createTag(JdbcFs.java:1747) ~[chimera-2.14.0-SNAPSHOT.jar:2.14.0-SNAPSHOT]
        ... 11 common frames omitted

**Comment by gbehrmann** [comment] 2015-06-19 14:12
Sounds like something for @kofemann.

**Comment by alrossi** [comment] 2015-06-19 14:13
@gbehrmann yes, I mentioned this at the last meeting, so he knows about it.

**Comment by kofemann** [comment] 2015-06-22 13:17
Hi Al, 

could you please check with https://rb.dcache.org/r/8352/

I can't reproduce with my shell/client.

**Comment by alrossi** [comment] 2015-06-22 13:22
I'll test your patch as soon as I fix the unit test problem for my webadmin patch.  Thanks, Tigran

**Comment by alrossi** [comment] 2015-06-22 16:05
@kofemann Works for me!

**Comment by kofemann** [comment] 2015-06-23 06:25
fixed with 0dc4063

**Closed by kofemann** 2015-06-23 06:25 UTC
Labels: bug
