### ISSUE TITLE
Ssh2Admin -> AdminPublicKeyAuthenticator not checking if user belongs to Admin group

### ISSUE THREAD

**Issue by solen0id** [dCache/dcache#3425] opened 2017-08-07 10:09 UTC
Hey all,

It looks like the AdminPublicKeyAuthenticator.authenticate() method is not checking if the users GID belongs to the admin-group. When building for system test, this allowed me to log in as an arbitrary (and/or non-existent) user, as long as the public-key used to authenticate is present in authorized_keys. 

Is this something that would not occur in a production system with proper user management and is unique to the system test package?

**Comment by kofemann** [comment] 2017-08-07 11:06
The assumption is that people with public key in authorized_keys file are admins. In case of username+pass, any valid user can connect to the admin interface, but only admins will be let in. IOW, looks like it works as designed.

**Comment by stefaus** [comment] 2017-08-07 20:56
I think the AdminPublicKeyAuthenticator should at very least check if the username belongs to an existing user, better if belongs to admin group.
Optional would be to bind public keys to usernames in authorized_keys2 file, to avoid possible impersonation fraud.

**Comment by kofemann** [comment] 2017-08-08 08:15
Your are right. We do not check, that the key matches the user. This is of course if not correct.

**Comment by paulmillar** [comment] 2017-11-10 14:51
I think the original topic (no checking if user member-of admin group) has been dealt with by @kofemann comment "The assumption is that people with public key in authorized_keys file are admins." So this works as expected.

The additional work (binding identity in authorized_keys2 file to user identity) is certainly appreciated, but slightly different from the original question.

Therefore, I think we can close this issue.

**Closed by paulmillar** 2017-11-10 14:51 UTC
Labels: question, wontfix
