### ISSUE TITLE
root vs xroot TURL ? 

### ISSUE THREAD

**Issue by chaen** [dCache/dcache#6372] opened 2021-12-14 13:52 UTC
Hi,

I just noticed that dCache will not return a `root` URL, even if asked politely :-) 

```bash
bash-4.2$ gfal-xattr -D "SRM PLUGIN:TURL_PROTOCOLS=root" srm://lhcbsrm-disk-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/zozo.xml user.replicas

gfal-xattr error: 95 (Operation not supported) - srm-ifce err: Operation not supported, err: [SE][PrepareToGet][SRM_NOT_SUPPORTED] httpg://lhcbsrm-disk-kit.gridka.de:8443/srm/managerv2: Protocol(s) not supported: [root]
```

It works fine for `xroot` though

```
bash-4.2$ gfal-xattr -D "SRM PLUGIN:TURL_PROTOCOLS=xroot" srm://lhcbsrm-disk-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/zozo.xml user.replicas

xroot://lhcbsrm-kit.gridka.de:1094/pnfs/gridka.de/lhcb/LHCb_USER/lhcb/user/c/chaen/zozo.xml
```

My understanding was that `root` and `xroot` are now equivalent.
Is it by design that only one works ? I don't really mind, it's just to satisfy my curiosity. (FYI, `Storm` returns `root` regardless of what is asked)

Cheers

**Comment by paulmillar** [comment] 2021-12-14 14:56
This actually changed some time ago (March 2020) and all dCache versions since v6.2 now support `xroot` as the way to ask for a xroot-protocol compatible TURL.

Before this, `root` was the only way to request an xroot-protocol URL.

You can also ask for an `xroots` protocol, but that requires the TLS support in the xroot door to be enabled.

It's, perhaps, arguable that this is a regression: that dCache should support both `root` and `xroot`.

**Comment by simonmichal** [comment] 2021-12-15 11:05
@paulmillar : to add my 2 cents, the XRootD framework supports both URL prefixes `root` and `xroot` and considers them equivalent.

**Comment by kofemann** [comment] 2021-12-15 15:17
Well, Technically, dCache support only xroot. If a ROOT uses **TRootFile**, then it will fail if `xroot` endpoint is returned. Yes, in mostases **TXNetFile** is used, that treats everything as `xroot`. IOW, dCache works as expected.

**Comment by alrossi** [comment] 2022-06-08 14:34
Closing on the basis of @kofemann 's answer

**Closed by alrossi** 2022-06-08 14:34 UTC
Labels: xroot
