### ISSUE TITLE
API: restore items array is empty, does not list active restore

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#4554] opened 2019-01-28 12:32 UTC
Dear dCache devs,

We're preparing for the upgrade from 3.2 to 4.2. Previously we collected some metrics from the webadmin interface, and now I'm converting our scripts to use the API. I'm testing with the 5.1 snapshot.

I've started a restore, which lists as `active` with `rh ls`:

    [root@dolphin12 ~]# dcache-admin-command dolphin12_genericstage 'rh ls'
    72e8e938-6710-49b2-a807-9f2c0e551be9 ACTIVE Mon Jan 28 13:05:17 CET 2019 Mon Jan 28 13:05:17 CET 2019 0000FF229D43C3D146569ADE8E5BF7E68BF4 generic:tape

(dcache-admin-command is a wrapper we created.)
I appended a `sleep 60m` to our HSM script so that it doesn't disappear immediately.

But I can't find it in the API:

    curl -X GET "https://dolphin12.grid.surfsara.nl:20443/api/v1/restores?sort=pool%2Cstarted" -H  "accept: application/json" -H  "authorization: Basic ******************"

Result: a 200 code with:

    {
      "items": [],
      "currentOffset": 0,
      "nextOffset": -1,
      "currentToken": "5999ff85-8e8b-4ad2-82f6-0c03ea1adc1a",
      "timeOfCreation": 1548677649115
    }

I would expect the items array not to be empty, but instead to show the restore request that is active.

I authenticated with apiuser#admin and the corresponding password. The apiuser is listed in gPlazma as a member of the admin group.

Could this be a bug?

Kind regards,
Onno

**Comment by alrossi** [comment] 2019-01-28 13:36
Hi Onno,

before addressing this issue as a bug, could I just ask (to make sure):  what is the property:

```frontend.authz.unlimited-operation-visibility```

set to?

(see https://www.dcache.org/manuals/Book-5.0/config-frontend.shtml,

#  ---- Determines whether operations exposing file information
#       can be viewed by non-admin users.
#
#       When false (default), restores, queue operations on the pools,
#       billing records, and transfers which are not owned by the user
#       and are not anonymous can only be seen by admins.
#
#       Setting this value to true allows all users access
#       to this information.
#
(one-of?true|false)frontend.authz.unlimited-operation-visibility=false


Thanks, Al

**Comment by onnozweers** [comment] 2019-01-28 13:39
Hi Al,

Thanks for your quick response. That configuration value is the default:

    [root@dolphin12 /etc/dcache]# grep -s frontend.authz.unlimited-operation-visibility * layouts/* /usr/share/dcache/defaults/*
    /usr/share/dcache/defaults/frontend.properties:(one-of?true|false)frontend.authz.unlimited-operation-visibility=false

Thanks,
Onno

**Comment by alrossi** [comment] 2019-01-28 13:40
Also, another note:  there will be a delay in the registering of the transfer/restore on the frontend, as that info is cached and refreshed every minute (this was also the case with the old web interface).

Al

**Comment by onnozweers** [comment] 2019-01-28 13:42
Hi Al,

I suspected there could be a delay, and that's why I appended a `sleep 60m` to our HSM script, so that there would be plenty of time for it to show up.

Thanks,
Onno

**Comment by alrossi** [comment] 2019-01-28 13:43
OK, so then the issue is whether or not to authenticate as admin when doing curl.   If that is not desirable, then the property should probably be set to true. 

Al

**Comment by alrossi** [comment] 2019-01-28 13:50
P.S., I need to talk to Olufemi to see if he has made any progress on allowing admin authentication via a credential instead of user password.   Without that option, scripting against the RESTful interface constrains one to set that property to true.   This is not optimal, obviously.

**Comment by onnozweers** [comment] 2019-01-28 13:52
I tried setting frontend.authz.unlimited-operation-visibility to true, but that does not seem to make any difference. I waited 2 minutes for a new restore to show up, but no luck.

**Comment by alrossi** [comment] 2019-01-28 13:54
Does the restore show up in dcache-view on the restores page?

**Comment by alrossi** [comment] 2019-01-28 13:58
Also, sorry to be pedantic, but I assume you did set the property on the frontend domain and restarted that domain.

**Comment by onnozweers** [comment] 2019-01-28 14:04
Yes, I did. :-)

The dCache-View restore list is empty too (logged in as myself this time, and took the admin role).

I use curl to talk to the API (as well as the button "try it out", same results). With curl, I use --netrc and I have the credentials in the .netrc file, something like this:

    [root@dolphin12 ~]# cat .netrc 
    machine dolphin12.grid.surfsara.nl login apiuser#admin password mypassword

And that seems to work perfectly, except for the lists to be empty.

**Comment by alrossi** [comment] 2019-01-28 14:05
At Fermi, we run with the property set to true.  I just tested the curl command both through the swagger interface and on the command line, and all the restores show up.

Fermi is running 4.2, but I don't believe there have been any changes to the RESTful services from 4.2 to 5.1

**Comment by alrossi** [comment] 2019-01-28 14:10
OK, then there seems to be something else wrong here, though without more details it will be hard to reproduce your problem.

To recap (now that I reread your initial message):

You started a restore, authenticated using user/password.   rh ls shows the restore, but REST does not.

Then you switched to non admin with the property set to true.  Same result.

This could be a regression in 5.1.   Would it be possible for you to perhaps test with the latest 4.2?

Thanks, Al

**Comment by onnozweers** [comment] 2019-01-28 14:21
I'd like to test on our test server which now has 5.1 snapshot; setting up a new test server would take ages. Is there a downgrade procedure? Something along the lines of `database rollback` perhaps?

**Comment by onnozweers** [comment] 2019-01-28 14:31
Can I use a frontend 4.2 with a 3.2 instance?

**Comment by alrossi** [comment] 2019-01-28 14:43
No, unfortunately there are pool incompatibilities.

I just tested 5.1.0 SNAPSHOT (we had it running on another testbed) and everything looks just fine.  

You said that neither restores nor transfers are showing up, correct?

Do you see anything (exceptions, etc.) in the frontendDomain log?

what if you do (in the admin shell):

\s <frontend> transfers refresh
\s <frontend> transfers ls

Do you see anything?  (assuming you are running a transfer; unfortunately, there is no restores ls at the moment in the admin shell).

**Comment by onnozweers** [comment] 2019-01-28 14:52
We don't have a `transfers` cell. Could that be a problem? We have these on our test server:

```
[dolphin12] (local) admin > \l
acm
alarms
billing
cleaner
DCap-dolphin12
DCap-gsi-dolphin12
dolphin12_genericdisk
dolphin12_genericstage
dolphin12_generict1d1
dolphin12_generictape
Frontend-dolphin12
GFTP-dolphin12
gPlazma
history
info
NFS-dolphin12
PinManager
PnfsManager
PoolManager
RemoteTransferManager
SpaceManager
SRM-dolphin12
SrmManager
topo
webdav2880-dolphin12
webdav2881-dolphin12
webdav2882-dolphin12
webdav2883-dolphin12
webdav2884-dolphin12
webdav443-dolphin12
```

**Comment by alrossi** [comment] 2019-01-28 14:54
Sorry, the markdown swallowed the command.   I originally wrote:

``` \s <frontend> transfers refresh
      \s <frontend> transfers ls```

Apologies

**Comment by onnozweers** [comment] 2019-01-28 15:03
Aha, thanks.

I have the srmcp loop still running. I tried this a hundred times:

    [dolphin12] (local) admin > \s Frontend-dolphin12 transfers ls
    TOTAL TRANSFERS : 0

Always the same result.

I had a look at the frontend log:

```
2019-01-28 15:18:09 Launching /usr/bin/java -server -Xmx1g -XX:MaxDirectMemorySize=1g -Dsun.net.inetaddr.ttl=1800 -Dorg.globus.tcp.port.range=20000,25000 -Dorg.dcache.dcap.port=0 -Dorg.dcache.ftp.log-aborted-transfers=false -Dorg.dcache.net.tcp.portrange=33000:34500 -Djava.security.krb5.realm= -Djava.security.krb5.kdc= -Djavax.security.auth.useSubjectCredsOnly=false -Djava.security.auth.login.config=/etc/dcache/jgss.conf -Dcontent.types.user.table=/etc/dcache/content-types.properties -Dzookeeper.sasl.client=false -Dcurator-dont-log-connection-problems=true -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/frontend-dolphin12Domain-oom.hprof -XX:+UseCompressedOops -javaagent:/usr/share/dcache/classes/aspectjweaver-1.9.2.jar -Djava.awt.headless=true -DwantLog4jSetup=n -Djdk.tls.ephemeralDHKeySize=2048 -Ddcache.home=/usr/share/dcache -Ddcache.paths.defaults=/usr/share/dcache/defaults org.dcache.boot.BootLoader start frontend-dolphin12Domain
28 Jan 2019 15:18:15 (Frontend-dolphin12) [] None or multiple beans found in Spring context for type class org.dcache.restful.resources.doors.DoorsResources, skipping the type.
```

No idea what the second line means.

**Comment by alrossi** [comment] 2019-01-28 15:08
I don't think that second line is related to this problem, but it could be that you have two .jar files for the frontend service (installation did not remove the old one?)

On the testbed node with the frontend, what does

```
[root@fndcatemp1 ~]# ls -l /usr/share/dcache/classes/*frontend*
```

show?

**Comment by onnozweers** [comment] 2019-01-28 15:11
Only one:

```
[root@dolphin12 /var/log]# ls -l /usr/share/dcache/classes/*frontend*
-rw-r--r-- 1 root root 318948 Jan 18 11:02 /usr/share/dcache/classes/dcache-frontend-5.1.0-SNAPSHOT.jar
```

**Comment by alrossi** [comment] 2019-01-28 15:12
How about

```
ls -l /usr/share/dcache/classes/*restful*
```

?

**Comment by onnozweers** [comment] 2019-01-28 15:13
None, is that OK?

```
[root@dolphin12 /var/log]# ls -l /usr/share/dcache/classes/*restful*
ls: cannot access /usr/share/dcache/classes/*restful*: No such file or directory
```

**Comment by alrossi** [comment] 2019-01-28 15:15
Yes, that's what you want.   I thought you might possibly have the old jar before it was renamed to frontend.

Could you maybe up the frontend logging to TRACE and then after a few minutes attach the output?

I am continuing to scratch my head.

**Comment by onnozweers** [comment] 2019-01-28 15:32
Here's the log at trace level.

[frontend-trace.log](https://github.com/dCache/dcache/files/2803683/frontend-trace.log)

The log should include this action:

    curl --netrc -X GET "https://dolphin12.grid.surfsara.nl:20443/api/v1/restores" -H  "accept: application/json" --fail --silent --show-error

**Comment by onnozweers** [comment] 2019-01-28 15:34
Oh by the way, I didn't leave it a trace for a few minutes... Is that important?

**Comment by alrossi** [comment] 2019-01-28 15:58
Yes, please run it at TRACE for about 5 minutes.

What I am looking for:

1.   What events are arriving (addToEventQueue)
2.  Whether there are any collection failures (these are not reported at ERROR, but at INFO/DEBUG, because they are technically not fatal ... could be transient connection issues, etc.).

All I see in your log so far are the HTTP Request/Response processing, which is not what I believe is going wrong.  There is something preventing the collection and caching of information from other services.

For restores, in particular, the pool manager should periodically be sending out notifications about the restores it knows about.  Frontend is subscribed to this topic, should be getting events and processing them.

**Comment by alrossi** [comment] 2019-01-28 16:05
Oh, of course please continue to run the restore requests if there aren't any currently being processed :-)

**Comment by onnozweers** [comment] 2019-01-28 16:18
Here's 5 minute of TRACE, while a restore was running.

[frontend-trace-2.log](https://github.com/dCache/dcache/files/2803848/frontend-trace-2.log)

**Comment by alrossi** [comment] 2019-01-28 16:48
Inspecting and comparing.

In the meantime, you said you did rh ls (on the pool) and saw the transfers.  But what about:

```
\sp rc ls
```

(i.e., PoolManager)?

(The frontend gets its restore info from the PoolManager, not the individual pools.)

**Comment by alrossi** [comment] 2019-01-28 18:24
I cannot see anything telltale from the log.   

Wrt the restores, I would ask again to double-check the PoolManager (``rc ls``).   I assume your script is using some protocol like srm to stage the files, and not ``rh restore <pnfsid>`` on the pools.  Restores initiated by the latter command will not show up in the frontend.

**Comment by onnozweers** [comment] 2019-01-29 09:12
Actually, I did `rh restore`. Oopsy! I tried now with srm-bring-online, and:

```
{
  "items": [
    {
      "key": "00007ECA581B38744AA2A0433A1FDAA873F5@0.0.0.0/0-DCap/*",
      "pnfsId": "00007ECA581B38744AA2A0433A1FDAA873F5",
      "path": "/users/onno/tape/friedweasel.jpg",
      "subnet": "@0.0.0.0/0-DCap/*",
      "poolCandidate": "<unknown>",
      "started": 1548752817290,
      "clients": 1,
      "retries": 0,
      "status": "Suspended (pool unavailable) 01.29 10:06:57",
      "error": 0,
      "errorMessage": "",
      "valid": true
    }
  ],
  "currentOffset": 0,
  "nextOffset": -1,
  "currentToken": "0ff77e13-4dae-4a21-a00e-d4dfd8c2c3b4",
  "timeOfCreation": 1548752896872
}
```

Success!

**Comment by onnozweers** [comment] 2019-01-29 10:36
The array of transfers is still empty though. I started a curl download with `--limit-rate` to slow it down and make it last 90 minutes.

```
onno$ curl --capath /etc/grid-security/certificates/ --cert $X509_USER_PROXY --cacert $X509_USER_PROXY --limit-rate 200k --fail --location https://dolphin12.grid.surfsara.nl:2880/users/onno/disk/test-1GB --output /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  5 1024M    5 52.5M    0     0   200k      0  1:27:22  0:04:28  1:22:54  202k
```

It is listed in the pool:

```
[root@dolphin12 /etc/grid-security]# dcache-admin-command dolphin12_genericdisk 'mover ls'
2044 : RUNNING : 000012C999D083CF4178BC13653B94F0331D IoMode=[READ] h={Http} bytes=90505216 time/sec=130 LM=8 si={generic:disk}
```

But not in the API (with `#admin credentials`, and `frontend.authz.unlimited-operation-visibility=true` in the frontend config, and after waiting for ~10 minutes):

```
[root@dolphin12 /etc/grid-security]# curl --netrc -X GET "https://dolphin12.grid.surfsara.nl:20443/api/v1/transfers" -H  "accept: application/json" --fail --silent --show-error ; echo
{
  "items" : [ ],
  "currentOffset" : 0,
  "nextOffset" : -1,
  "currentToken" : "7aa80ad8-54f5-4488-81fa-0ade71f0c0f7",
  "timeOfCreation" : 1548757880940
}
```

**Comment by alrossi** [comment] 2019-01-29 13:43
P.S, just as a side note.

If you want to see the equivalent of rh ls on a pool through REST, do not use the restore api.  Use the pool api.  For example 

```
curl -X GET "https://fndca3a.fnal.gov:3880/api/v1/pools/rw-stkendca49a-6/nearline/queues?type=stage&offset=0&sort=class%2Ccreated" -H  "accept: application/json"
```

(check Swagger for full details)

**Comment by alrossi** [comment] 2019-01-29 13:46
Also, I think you said you used srmcp yesterday, but just in case, could you try out a different protocol from webdav? (just trying to see if that makes a difference).

**Comment by onnozweers** [comment] 2019-01-29 13:54
> If you want to see the equivalent of `rh ls` on a pool through REST, do not use the restore api. Use the pool api.

Thanks, that is good to know.

I tried this:

    curl -X GET "https://dolphin12.grid.surfsara.nl:20443/api/v1/pools/dolphin12_genericdisk/movers?offset=0&sort=door%2CstartTime" -H "accept: application/json"

And it listed my running WebDAV transfer.

```
[
  {
    "pnfsId": "000012C999D083CF4178BC13653B94F0331D",
    "mode": "[READ]",
    "door": "webdav2880-dolphin12@webdav2880-dolphin12Domain",
    "storageClass": "generic:disk",
    "state": "RUNNING",
    "bytes": 142286848,
    "timeInSeconds": 383526,
    "startTime": 1548769424823,
    "submitTime": 1548769424823,
    "lastModified": 1548769787913,
    "moverId": 2045
  }
]
```

The `timeInSeconds` looks a bit weird though. Isn't that milliseconds?

**Comment by onnozweers** [comment] 2019-01-29 13:55
I noticed there is a component called transfer manager. We don't run that. What does it do?

**Comment by alrossi** [comment] 2019-01-29 13:55
Doesn't look like I can access that page.  But no matter.

This is a webdav transfer, right?  Would it be possible to try a different protocol?  I have a suspicion something changed with webdav.  I think somehow the collector in the frontend might be affected.

**Comment by onnozweers** [comment] 2019-01-29 14:07
I started a GridFTP transfer, but even a 1 GB file is done in 1.4 second. So I started one and immediately pressed Ctrl+Z. That worked for the 2288 web interface and for the `/pools/dolphin12_genericdisk/movers` API call:

```
[
  {
    "pnfsId": "000012C999D083CF4178BC13653B94F0331D",
    "queue": "gridftp_queue",
    "mode": "[READ]",
    "door": "GFTP-dolphin12-AAWAmUD6ggA@ftp-dolphin12Domain",
    "storageClass": "generic:disk",
    "state": "RUNNING",
    "bytes": 339912252,
    "timeInSeconds": 64890,
    "startTime": 1548770592128,
    "submitTime": 1548770592128,
    "lastModified": 1548770592968,
    "moverId": 2047
  }
]
```

The `/transfers` list is still empty though. So the problem is not WebDAV specific.

**Comment by alrossi** [comment] 2019-01-29 16:09
Onno,

just to let you know ... I have done a fresh deploy of the tip of master and also 5.0.2 and can confirm that there is an issue with transfers.   I am working on this to see if I can find the problem.

Al

**Comment by onnozweers** [comment] 2019-01-29 16:49
Hi Al,

Good to hear. Thanks for all the hard work!

Kind regards,
Onno

**Comment by alrossi** [comment] 2019-01-29 17:33
Onno,

if I provided you with a dcache-frontend.jar with a potential fix, could you deploy it, restart and see if that fixes it for you?

Al

**Comment by onnozweers** [comment] 2019-01-30 10:07
Hi Al, your .jar fixes the issue!

```
{
  "items": [
    {
      "cellName": "webdav2880-dolphin12",
      "domainName": "webdav2880-dolphin12Domain",
      "serialId": 1548842676652000,
      "protocol": "HTTP-1.1",
      "process": "",
      "pnfsId": "000012C999D083CF4178BC13653B94F0331D",
      "path": "/users/onno/disk/test-1GB",
....
  "timeOfCreation": 1548842719669
}
```

**Comment by alrossi** [comment] 2019-01-30 13:20
Turns out it was a silly bug (nine times out of ten, they are).

Thanks for being a very cooperative guinea pig :-).     Patch will be included in next release cycle.

**Comment by onnozweers** [comment] 2019-01-30 13:23
Thank you for spending so much time to fix this, and to troubleshoot my `rh restore` error.

Should we document somewhere that `rh restore` does not show up in the /restores API call?

**Comment by alrossi** [comment] 2019-01-30 13:30
Yes, that might be a good idea.  I assumed (wrongly) this was known because it was true for the old tape-restores pages (httpd, webadmin) as well.

I'll add this to the frontend documentation.

**Comment by alrossi** [comment] 2019-01-30 13:32
I'll also fix the name of the field (milliseconds, not seconds) in the stage JSON output.   I think that also applies to flush and remove, not sure, but I'll recheck all of this.  Thanks for catching that.

**Comment by alrossi** [comment] 2019-02-04 20:19
Resolved with merge.  Fix is in next release.

**Closed by alrossi** 2019-02-04 20:19 UTC
