### ISSUE TITLE
org.springframework.jdbc.CannotGetJdbcConnectionException

### ISSUE THREAD

**Issue by martbhell** [dCache/dcache#1726] opened 2015-07-01 06:32 UTC
This happened during restarts of dCache (on several servers):

dCache 2.10.34
openjdk
SL 6.6

The Domain where this logfile is from run these services:

[srm-madhatterDomain]
[srm-madhatterDomain/srm]
[srm-madhatterDomain/spacemanager]
[srm-madhatterDomain/transfermanagers]

<pre>
2015-06-30 09:03:44 Process terminated

2015-06-30 09:32:24 Launching /usr/bin/java -server -Xmx2048m -XX:MaxDirectMemorySize=512m -Dsun.net.inetaddr.ttl=1800 -Dorg.globus.tcp.port.range=20000,25000 -Dorg.dcache.dcap.port=0 -Dorg.d
cache.net.tcp.portrange=20000:25000 -Dorg.globus.jglobus.delegation.cache.lifetime=30000 -Dorg.globus.jglobus.crl.cache.lifetime=60000 -Djava.security.krb5.realm= -Djava.security.krb5.kdc= -D
javax.security.auth.useSubjectCredsOnly=false -Djava.security.auth.login.config=/etc/dcache/jgss.conf -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/dcache/srm-madhatterDomain-oom.
hprof -javaagent:/usr/share/dcache/classes/aspectjweaver-1.8.1.jar -Djava.awt.headless=true -DwantLog4jSetup=n -Ddcache.home=/usr/share/dcache -Ddcache.paths.defaults=/usr/share/dcache/defaul
ts org.dcache.boot.BootLoader start srm-madhatterDomain
INFO  - dcache.conf:47: Property my.log.format.syslog is not a standard property
INFO  - dcache.conf:48: Property my.log.host.syslog is not a standard property
INFO  - dcache.conf:49: Property my.log.level.syslog is not a standard property
30 Jun 2015 09:33:55 (SRM-madhatter) [10.11.3.145:36769] Problem while establishing secure connection: java.net.SocketTimeoutException: Read timed out
30 Jun 2015 09:34:27 (c-dCacheDomain-101) [] Sleeping 18 seconds
30 Jun 2015 09:34:49 (lm) [] Problem in 'whereIs' request : java.io.IOException: Request timed out
30 Jun 2015 09:34:50 (c-dCacheDomain-101) [] Failed to connect to dCacheDomain: Timeout querying location manager
30 Jun 2015 09:34:50 (c-dCacheDomain-101) [] Sleeping 18 seconds
30 Jun 2015 09:35:03 (SRM-madhatter) [10.11.3.135:44312] Problem while establishing secure connection: java.net.SocketTimeoutException: Read timed out
30 Jun 2015 09:35:13 (lm) [] Problem in 'whereIs' request : java.io.IOException: Request timed out
30 Jun 2015 09:35:13 (SRM-madhatter) [10.11.3.107:60585] Problem while establishing secure connection: java.net.SocketTimeoutException: Read timed out
30 Jun 2015 09:35:14 (c-dCacheDomain-101) [] Failed to connect to dCacheDomain: Timeout querying location manager
30 Jun 2015 09:35:14 (c-dCacheDomain-101) [] Sleeping 20 seconds
30 Jun 2015 09:35:29 (SRM-madhatter) [10.11.3.107:60586] Problem while establishing secure connection: java.net.SocketTimeoutException: Read timed out
30 Jun 2015 09:35:38 (lm) [] Problem in 'whereIs' request : java.io.IOException: Request timed out
30 Jun 2015 09:35:39 (c-dCacheDomain-101) [] Failed to connect to dCacheDomain: Timeout querying location manager
30 Jun 2015 09:35:39 (c-dCacheDomain-101) [] Sleeping 5 seconds
30 Jun 2015 09:35:45 (lm) [] Problem in 'whereIs' request : java.io.IOException: Network is unreachable
30 Jun 2015 09:35:48 (SRM-madhatter) [10.12.100.13:56702] Client disconnected before SRM response was sent.
30 Jun 2015 09:35:48 (SRM-madhatter) [109.105.124.161:37557] Client disconnected before SRM response was sent.
30 Jun 2015 09:35:48 (SRM-madhatter) [10.12.100.19:34071 E2Q:91:srm2:prepareToPut] Request was interrupted
30 Jun 2015 09:35:48 (SRM-madhatter) [10.12.100.14:38414] Client disconnected before SRM response was sent.
30 Jun 2015 09:35:48 (SRM-madhatter) [10.12.100.19:34071] Client disconnected before SRM response was sent.
30 Jun 2015 09:35:48 (SRM-madhatter) [10.12.100.2:42858] Client disconnected before SRM response was sent.
30 Jun 2015 09:35:48 (SRM-madhatter) [188.185.227.41:48550 E2Q:106:srm2:ls] Please report this failure to support@dcache.org
org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Interrupted during connection acquisition
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) ~[spring-jdbc-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:630) ~[spring-jdbc-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:695) ~[spring-jdbc-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:727) ~[spring-jdbc-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:737) ~[spring-jdbc-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:787) ~[spring-jdbc-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.dcache.srm.request.sql.DatabaseRequestCredentialStorage.getRequestCredentialByCondition(DatabaseRequestCredentialStorage.java:207) ~[srm-server-2.10.34.jar:2.10.34]
        at org.dcache.srm.request.sql.DatabaseRequestCredentialStorage.getRequestCredential(DatabaseRequestCredentialStorage.java:244) ~[srm-server-2.10.34.jar:2.10.34]
        at org.dcache.srm.request.RequestCredential.newRequestCredential(RequestCredential.java:144) ~[srm-server-2.10.34.jar:2.10.34]
        at org.dcache.srm.server.SrmAuthorizer.getRequestCredential(SrmAuthorizer.java:200) ~[srm-server-2.10.34.jar:2.10.34]
        at org.dcache.srm.server.SRMServerV2.dispatch(SRMServerV2.java:263) [srm-server-2.10.34.jar:2.10.34]
        at org.dcache.srm.server.SRMServerV2.handleRequest(SRMServerV2.java:239) [srm-server-2.10.34.jar:2.10.34]
        at org.dcache.srm.server.SRMServerV2.srmLs(SRMServerV2.java:453) [srm-server-2.10.34.jar:2.10.34]
        at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
        at org.apache.axis.providers.java.RPCProvider.invokeMethod(RPCProvider.java:397) [axis-1.4.jar:na]
        at org.dcache.srm.util.LoggingRPCProvider.invokeMethod(LoggingRPCProvider.java:51) [srm-server-2.10.34.jar:2.10.34]
        at org.apache.axis.providers.java.RPCProvider.processMessage(RPCProvider.java:186) [axis-1.4.jar:na]
        at org.apache.axis.providers.java.JavaProvider.invoke(JavaProvider.java:323) [axis-1.4.jar:na]
        at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32) [axis-1.4.jar:na]
        at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118) [axis-1.4.jar:na]
        at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83) [axis-1.4.jar:na]
        at org.apache.axis.handlers.soap.SOAPService.invoke(SOAPService.java:454) [axis-1.4.jar:na]
        at org.apache.axis.server.AxisServer.invoke(AxisServer.java:281) [axis-1.4.jar:na]
        at org.apache.axis.transport.http.AxisServlet.doPost(AxisServlet.java:699) [axis-1.4.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) [javax.servlet-3.0.0.v201112011016.jar:na]
        at org.apache.axis.transport.http.AxisServletBase.service(AxisServletBase.java:327) [axis-1.4.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [javax.servlet-3.0.0.v201112011016.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [jetty-servlet-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503) [jetty-servlet-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557) [jetty-security-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [jetty-servlet-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.dcache.util.JettyGSIConnector$GsiConnection.run(JettyGSIConnector.java:572) [dcache-core-2.10.34.jar:2.10.34]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.15.v20140411.jar:8.1.15.v20140411]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.sql.SQLException: Interrupted during connection acquisition
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:199) ~[HikariCP-java6-2.0.1.jar:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:93) ~[HikariCP-java6-2.0.1.jar:na]
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111) ~[spring-jdbc-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77) ~[spring-jdbc-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        ... 53 common frames omitted
Caused by: java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedLongSynchronizer.doAcquireSharedNanos(AbstractQueuedLongSynchronizer.java:815) ~[na:1.7.0_79]
        at java.util.concurrent.locks.AbstractQueuedLongSynchronizer.tryAcquireSharedNanos(AbstractQueuedLongSynchronizer.java:1103) ~[na:1.7.0_79]
        at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:146) ~[HikariCP-java6-2.0.1.jar:na]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:169) ~[HikariCP-java6-2.0.1.jar:na]
        ... 56 common frames omitted
30 Jun 2015 09:35:48 (SRM-madhatter) [188.185.227.41:48550] Client disconnected before SRM response was sent.
30 Jun 2015 09:35:48 (SRM-madhatter) [188.185.227.41:48550] Client disconnected before SRM response was sent.
30 Jun 2015 09:35:48 (SRM-madhatter) [] 1 threads could not be stopped
30 Jun 2015 09:35:48 (SRM-madhatter) [10.12.100.21:49727 E2Q:84:srm2:ls:-2073365550:-2073365549] Persistence of request -2073365549 failed, queue is too long.
30 Jun 2015 09:35:48 (SRM-madhatter) [10.12.100.19:34068 E2Q:85:srm2:ls:-2073365548:-2073365547] Persistence of request -2073365547 failed, queue is too long.
30 Jun 2015 09:35:49 (System) [] Timeout waiting for SRM-madhatter
30 Jun 2015 09:35:49 (System) [] Thread: Timer-0 [AD-] (5) TIMED_WAITING
30 Jun 2015 09:35:49 (System) []     java.lang.Object.wait(Native Method)
30 Jun 2015 09:35:49 (System) []     java.util.TimerThread.mainLoop(Timer.java:552)
30 Jun 2015 09:35:49 (System) []     java.util.TimerThread.run(Timer.java:505)
30 Jun 2015 09:35:49 (System) [] Thread: Job expiration [AD-] (5) TIMED_WAITING
30 Jun 2015 09:35:49 (System) []     java.lang.Object.wait(Native Method)
30 Jun 2015 09:35:49 (System) []     java.util.TimerThread.mainLoop(Timer.java:552)
30 Jun 2015 09:35:49 (System) []     java.util.TimerThread.run(Timer.java:505)
30 Jun 2015 09:35:49 (System) [] Thread: jetty-srm-56 [A-I] (5) RUNNABLE
30 Jun 2015 09:35:49 (System) []     java.net.SocketInputStream.socketRead0(Native Method)
30 Jun 2015 09:35:49 (System) []     java.net.SocketInputStream.read(SocketInputStream.java:152)
30 Jun 2015 09:35:49 (System) []     java.net.SocketInputStream.read(SocketInputStream.java:122)
30 Jun 2015 09:35:49 (System) []     org.globus.gsi.gssapi.SSLUtil.read(SSLUtil.java:41)
30 Jun 2015 09:35:49 (System) []     org.globus.gsi.gssapi.net.impl.GSIGssInputStream.readToken(GSIGssInputStream.java:70)
30 Jun 2015 09:35:49 (System) []     org.globus.gsi.gssapi.net.impl.GSIGssInputStream.readHandshakeToken(GSIGssInputStream.java:60)
30 Jun 2015 09:35:49 (System) []     org.globus.gsi.gssapi.net.impl.GSIGssSocket.readToken(GSIGssSocket.java:64)
30 Jun 2015 09:35:49 (System) []     org.globus.gsi.gssapi.net.GssSocket.authenticateServer(GssSocket.java:126)
30 Jun 2015 09:35:49 (System) []     org.globus.gsi.gssapi.net.GssSocket.startHandshake(GssSocket.java:146)
30 Jun 2015 09:35:49 (System) []     org.dcache.util.JettyGSIConnector$GsiConnection.run(JettyGSIConnector.java:566)
30 Jun 2015 09:35:49 (System) []     org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
30 Jun 2015 09:35:49 (System) []     org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
30 Jun 2015 09:35:49 (System) []     java.lang.Thread.run(Thread.java:745)
30 Jun 2015 09:35:49 (System) [] Thread: Timer-7 [AD-] (5) TIMED_WAITING
30 Jun 2015 09:35:49 (System) []     java.lang.Object.wait(Native Method)
30 Jun 2015 09:35:49 (System) []     java.util.TimerThread.mainLoop(Timer.java:552)
30 Jun 2015 09:35:49 (System) []     java.util.TimerThread.run(Timer.java:505)
30 Jun 2015 09:35:49 (System) [] Thread: Timer-8 [AD-] (5) TIMED_WAITING
30 Jun 2015 09:35:49 (System) []     java.lang.Object.wait(Native Method)
30 Jun 2015 09:35:49 (System) []     java.util.TimerThread.mainLoop(Timer.java:552)
30 Jun 2015 09:35:49 (System) []     java.util.TimerThread.run(Timer.java:505)

2015-06-30 09:43:09 Launching /usr/bin/java -server -Xmx2048m
</pre>

**Comment by gbehrmann** [comment] 2015-07-01 08:41
Thanks. In general, any failure during startup is causing such a message. The challenge is that we cannot reliably distinguish between bugs and other failures and to be on the safe site we log the entire stack trace. We will see if we can somehow address this, but it doesn't have high priority right now.

**Comment by gbehrmann** [comment] 2015-07-01 08:42
Essentially a duplicate of #1626.

**Comment by gbehrmann** [comment] 2015-11-22 12:11
Fixed by 60ddcf9370563c5d0dc01c4bc29002ae05fc235e.

**Closed by gbehrmann** 2015-11-22 12:11 UTC
Labels: bug
