### ISSUE TITLE
In web admin interface, max stores and max restores columns are zero instead of the real value

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#1638] opened 2015-06-10 10:54 UTC
In dCache 2.10, when we look at the web admin interface pool request queues, for instance here:
http://dcmain.grid.sara.nl:2288/webadmin/queueinfo
... we always see zeroes in the 'max stores' and 'max restores' columns, whatever the value in the pool is. The 'act' and 'que' columns seem to have the correct values.

The old style web interface has the same issue:
http://dcmain.grid.sara.nl:2288/queueInfo

In 2.6 this worked as expected.

**Comment by gbehrmann** [comment] 2015-06-10 12:46
Not a bug. The max values no longer exist as far as dCache is concerned. Queues for nearline storage are unbounded. Any limit is an implementation detail of a specific nearline storage plugin. This was noted in the 2.9.0 release notes:

> Since nearline storage request queuing is now no longer part of dCache, the maximum active requests limits are no longer reported to poolmanager. For some drivers, such a limit may not even exist. Pool selection has been updated to no longer rely on these values.

Thus the web pages also do not pick those values up anymore.

**Comment by onnozweers** [comment] 2015-06-12 08:07
Hi Gerd, 

Thanks for explaining. Then may I suggest the columns are removed instead of showing misleading information? Even showing a dash instead of a zero would be better, IMHO.

Kind regards
Onno

**Comment by gbehrmann** [comment] 2015-06-12 08:08
Okay, marking as a request for enhancement instead.

**Comment by gbehrmann** [comment] 2015-06-19 14:10
Al, could you have a look at applying the same fix to webadmin?

**Comment by alrossi** [comment] 2015-06-19 14:12
@gbehrmann Sure, Gerd.  But not immediately.  I can perhaps have a look this weekend.  OK?

**Comment by gbehrmann** [comment] 2015-06-19 14:19
Sure, no hurry.

**Comment by alrossi** [comment] 2015-06-21 17:12
patch https://rb.dcache.org/r/8338 @gbehrmann

**Comment by gbehrmann** [comment] 2015-06-22 09:17
@alrossi please submit pull requests for 2.10 to 2.13.

**Comment by alrossi** [comment] 2015-06-22 14:19
I have added null guards to a few places.

**Closed** 2015-06-23 13:08 UTC
Labels: enhancement
