### ISSUE TITLE
dcap NFS proxy fails to set EOF bit in WRITE-then-READ pattern

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#1949] opened 2015-11-17 10:28 UTC
The python NFS test `WRT5` using NFS 4.0 and writes some non-negligible amount of data, then reads it back.

When reading it back, the code does:

    eof = False
    newdata = ''
    while not eof:
        res = c.read_file(fh, len(newdata), len(data) - len(newdata), stateid)
        check(res, msg="READ with large amount of data")
        newdata += res.data
        eof = res.eof

Currently, dCache v2.10 and v2.11 uses a proxy for NFS v4.0 activity, using dcap protocol.  This proxy contains a bug where the EOF is not set when the client first writes data and then immediately reads it back.

The result of this bug is that the NFS test becomes stuck attempting to read zero bytes.

**Comment by kofemann** [comment] 2016-07-19 15:56
the issue is fixed in later versions of dcache, where proxy-io is implemented with NFS.

**Closed by kofemann** 2016-07-19 15:56 UTC
Labels: bug
