### ISSUE TITLE
Building dCache fails

### ISSUE THREAD

**Issue by xpinkyx** [dCache/dcache#5152] opened 2019-11-05 12:26 UTC
I've tried to build dcache (latest commit e228d41) and got some failures:

with _mvn package_ 

`[INFO] gPlazma 2 Name Service Switch plugin ............... FAILURE [  1.306 s]`

from modules/gplazma2-nsswitch/target/surefire-reports/org.dcache.gplazma.plugins.NsswitchTest.txt 
```
-------------------------------------------------------------------------------
Test set: org.dcache.gplazma.plugins.NsswitchTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.237 s <<< FAILURE! - in org.dcache.gplazma.plugins.NsswitchTest
initializationError(org.dcache.gplazma.plugins.NsswitchTest)  Time elapsed: 0.012 s  <<< ERROR!
org.objenesis.ObjenesisException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.IllegalAccessError: class jdk.internal.reflect.ConstructorAccessorImpl loaded by org.powermock.core.classloader.MockClassLoader @6f7fd0e6 cannot access jdk/internal/reflect superclass jdk.internal.reflect.MagicAccessorImpl
```

and with _mvn package -DskipTests_

```
[INFO] dCache docker packaging ............................ FAILURE [ 33.369 s]
[INFO] dCache FHS layout .................................. SKIPPED
[INFO] System tests ....................................... SKIPPED
[INFO] dCache archetypes base ............................. SKIPPED
[INFO] dCache Nearline Storage Plugin Archetype ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:52 min
[INFO] Finished at: 2019-11-05T12:57:53+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.7:build (default) on project dcache-docker: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dcache-docker
```

**Comment by onnozweers** [comment] 2019-11-05 12:35
Duplicate of #5149

**Comment by paulmillar** [comment] 2019-11-05 13:02
Which version of java are you using to build dCache?

**Comment by xpinkyx** [comment] 2019-11-05 13:14
I'm using openjdk 11.0.4

**Comment by onnozweers** [comment] 2019-11-05 13:16
> Duplicate of #5149

I take it back 😸

**Comment by paulmillar** [comment] 2019-11-05 13:21
Could you try again, but using OpenJDK v8?

I don't believe we are ready to build dCache with Java v11, just yet.

**Comment by xpinkyx** [comment] 2019-11-05 13:57
Okay, with java-version 1.8.0_222 same error with _mvn package -DskipTests_. _mvn package_ now fails on dcache-core:

```
ERROR] Failures: 
[ERROR]   ChecksumChannelTest.shouldUpdateChecksumSynchronizedForMultiThreadedWrites:245 
Expected: iterable containing [<2:edaef099d308bd2d337ddb26e37cdef6>]
     but: item 0: was <2:58502d6672c0fc599f88a16d57a79e6d>
[ERROR] Errors: 
[ERROR]   ChecksumChannelTest.shouldBeAbleToFillZeroRangesOfSizeGreater4Gb:285 » NoSuchMethod
[ERROR]   ChecksumChannelTest.shouldBeAbleToReadBackRangesOfSizeGreater4Gb:270 NoSuchMethod
[ERROR]   ChecksumChannelTest.shouldFillUpRangeGapsWithZerosOnGetChecksum:295 » NoSuchMethod
[ERROR]   ChecksumChannelTest.shouldReturnNullDigestOnDoubleWrites:139 NoSuchMethod java...
[ERROR]   ChecksumChannelTest.shouldSucceedIfWrittenOutOfOrderWithPosition:100 » NoSuchMethod
[ERROR]   ChecksumChannelTest.shouldSucceedIfWrittenOutOfOrderWithSingleBuffer:111 » NoSuchMethod
[ERROR]   ChecksumChannelTest.shouldUpdateChecksumOnlyForWrittenBytesOnIncompleteWritesWithSingleBufferAndPosition:182 » NoSuchMethod
[ERROR]   ConsistentReplicaStoreTest.shouldDeleteBrokenReplicasWithNoNameSpaceEntry:198->givenStoreHasFileOfSize:78 NoSuchMethod
[ERROR]   ConsistentReplicaStoreTest.shouldDeleteIncompleteReplicasWithNoNameSpaceEntry:165->givenStoreHasFileOfSize:78 NoSuchMethod
[ERROR]   ConsistentReplicaStoreTest.shouldDeleteIncompleteRestores:262->givenStoreHasFileOfSize:78 NoSuchMethod
[ERROR]   ConsistentReplicaStoreTest.shouldMarkMissingEntriesWithWrongSizeAsBroken:296->givenStoreHasFileOfSize:78 NoSuchMethod
[ERROR]   ConsistentReplicaStoreTest.shouldMarkNonTransientReplicasWithWrongSizeAsBroken:99->givenStoreHasFileOfSize:78 NoSuchMethod
[ERROR]   ConsistentReplicaStoreTest.shouldNotTalkToNameSpaceForIntactEntries:320->givenStoreHasFileOfSize:78 NoSuchMethod
[ERROR]   ConsistentReplicaStoreTest.shouldRecoverBrokenEntries:227->givenStoreHasFileOfSize:78 NoSuchMethod
[ERROR]   ConsistentReplicaStoreTest.shouldRegisterFileSizeAndLocationOnIncompleteUpload:132->givenStoreHasFileOfSize:78 NoSuchMethod
```
[...]
`[INFO] dCache Core ........................................ FAILURE [ 36.419 s]`
[...]
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:26 min
[INFO] Finished at: 2019-11-05T14:32:26+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project dcache-core: There are test failures.
[ERROR] 
[ERROR] Please refer to /xxxx/dcache/modules/dcache/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by paulmillar** [comment] 2019-11-05 18:47
This looks like you have out-of-date class files.  Could you try running with the `clean` goal?

Perhaps the safest option is to always run the `clean` goal before `package`; e.g.,

    mvn clean package

**Comment by xpinkyx** [comment] 2019-11-07 07:50
Tests are  now running without failure. But there is still a problem:

```
[INFO] dCache docker packaging ............................ FAILURE [ 15.705 s]
[INFO] dCache FHS layout .................................. SKIPPED
[INFO] System tests ....................................... SKIPPED
[INFO] dCache archetypes base ............................. SKIPPED
[INFO] dCache Nearline Storage Plugin Archetype ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:31 min
[INFO] Finished at: 2019-11-07T08:34:28+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.7:build (default) on project dcache-docker: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by paulmillar** [comment] 2019-11-07 10:26
Patch: https://rb.dcache.org/r/12024/

**Closed** 2019-11-07 13:53 UTC
Labels: build
