### ISSUE TITLE
Internal server error: org.dcache.webdav.WebDavException: Problem with transferred data: Early EOF

### ISSUE THREAD

**Issue by cfgamboa** [dCache/dcache#6358] opened 2021-12-13 21:49 UTC
The affected webdav door is:

dCache version
[root@dcdoor02 dcache]# rpm -qa |grep dcache
dcache-7.2.3-1.noarch

```
/var/log/dcache/webdav2-dcdoor02_httpsDomain.access:level=ERROR ts=2021-12-13T16:18:52.946-0500 event=org.dcache.webdav.request request.method=PUT request.url=https://dcgftp.usatlas.bnl.gov/pnfs/usatlas.bnl.gov/BNLT0D1/rucio/mc16_13TeV/df/56/AOD.14817647._001230.pool.root.1 response.code=500 socket.remote=192.108.68.22:58482 user-agent=dCache/6.2.34 user.mapped=6435:31152,69907[HUm3Jpgo:lg6tPqK9] transaction=door:WebDAV2-dcdoor02-2@webdav2-dcdoor02_httpsDomain:AAXTDZo8f8g:1639430259272000 duration=73702
/var/log/dcache/webdav2-dcdoor02_httpsDomain.log:13 Dec 2021 16:18:52 (WebDAV2-dcdoor02-2) [door:WebDAV2-dcdoor02-2@webdav2-dcdoor02_httpsDomain:AAXTDZo8f8g] Internal server error: org.dcache.webdav.WebDavException: Problem with transferred data: Early EOF

```
Here the affected door is shown in yellow, WebDav-dcdoor02, which is unbalanced compared to the other doors 

<img width="1358" alt="webdav-door02" src="https://user-images.githubusercontent.com/30438971/145894270-a1436d63-49e1-44b0-b0eb-f01426611a41.png">

**Comment by cfgamboa** [comment] 2021-12-14 19:58
Another sample of similar issue is reported here on this FTS transfer:
https://fts305.usatlas.bnl.gov:8449/var/log/fts3/transfers/2021-12-14/eosatlas.cern.ch__dcgftp.usatlas.bnl.gov/2021-12-14-1423__eosatlas.cern.ch__dcgftp.usatlas.bnl.gov__1152509244__8d2e4380-5a1a-11ec-a702-00163e1051a4


Looking at the logs of the elements involved, SRM, webdav door and pool. The file being transferred is removed of the system after the the checksum comparison between the initial request and the one being transferred at the pool does not match. A timeout reached appears to affect the completion of the file being copied There is a timeout reached 


The transfer is accepted by the BNL system:
```
12.14 07:44:53 [door:RemoteTransferManager@srm-dcsrm03Domain:request] ["usatlas1":6435:31152:unknown] [0000045A177FD7674DFBB35FC8E41DE02A0B,0] [/pnfs/usatlas.bnl.gov/BNLT0D1/rucio/mc20_13TeV/dd/60/AOD.27413837._001471.pool.root.1] bnlt0d1:BNLT0D1@osm 5897633 390 {24:"java.io.IOException: transfer cancelled: client went away"}
```
What is this error, ` {24:"java.io.IOException: transfer cancelled: client went away"} ` if the transfer just has started?

2. Data transfer starts around Tue, 14 Dec 2021 07:45:03 and the last transmission was around Tue, 14 Dec 2021  09:23:00, it seems that the transfer is widely fragmented and appears to reach a set timeout.

```
[root@dcdoor09 ~]# grep 0000045A177FD7674DFBB35FC8E41DE02A0B /var/log/dcache/dcdoor09oneDomain.log
14 Dec 2021 10:38:22 (dcdoor09_1) [door:WebDAV2-dcdoor18-2@webdav2-dcdoor18_httpsDomain:AAXTGo5JvWg RemoteTransferManager PoolAcceptFile 0000045A177FD7674DFBB35FC8E41DE02A0B] Transfer failed in post-processing: Checksum mismatch (expected=[1:2fd03f71], actual=[1:0e858978])
```

billing reports
```
12.14 10:38:22 [pool:dcdoor09_1:transfer] [0000045A177FD7674DFBB35FC8E41DE02A0B,0] [/pnfs/usatlas.bnl.gov/BNLT0D1/rucio/mc20_13TeV/dd/60/AOD.27413837._001471.pool.root.1] bnlt0d1:BNLT0D1@osm 1574293112 5897256 true {RemoteHttpsDataTransfer-1.1:https://eosatlas.cern.ch:443/eos/atlas/atlasdatadisk/rucio/mc20_13TeV/dd/60/AOD.27413837._001471.pool.root.1?copy_mode=pull} [door:RemoteTransferManager@srm-dcsrm03Domain:1639485893372-9539237] {10027:"java.nio.channels.ClosedByInterruptException; redirects [http://st-096-hh151512.cern.ch:8443/eos/atlas/atlasdatadisk/rucio/mc20_13TeV/dd/60/AOD.27413837._001471.pool.root.1?encURI=%26cap.sym%3DXpjuvx5GIyW2tNJ2pzZclEuDm5s%3D%26cap.msg%3Dm8Z3VY5oNWut5EnMnaxxxpIybc4X44uDVOfQFeBFhUnv8tRswTk1h7AmwyvkX8haSC2Nedox9aDu7tfz8POBn0EPCPag8Y3DdbF5NBjzgDOnLHJnWVhjBE7PrhucDh0eNKisclnm41Q91cq5cSx5JpkDZ0g2IryOXAbQryv1h6iPY2WAnRbSUiDxLUxagkhXKOkOHu7cH9OIubVLLcVmddk8dH7J7qMaYZQp5knvpaRfvA6U0HKeFESrw9RyL0coik4u0qlcpuPoTAEs9l5F2rQavOtHtG2C711gRaHG7I%2B8XeI34z3c%2F3roApzN1m1VCXlpu0eY1o2nkqvx%2BgpflcxBolGTbBReGBPRNh4hwOVKouv8c67KAio%2BJuzrK2RQ0V0jD9yTnb2%2B5tLKMzQltAeovJHYN8IGNAwH14uu4EDOyafVxZsZKcdK7SiQBe2TKZ6RBnyIXZVkgNUSXivRHuuu4%2F5BkeMUrCjGrwxdMdM9KiBSwXhLWGJqqP5PU4ZAyUr0eNbn%2BC17GEG8FbrA%2FulkXFKBv1xI4HFNtho17aBW4b6eieuZ0d3W3ZLLlgmj8999JX%2FQnOQ9fI4U2uJLANtG4YQGNa226%2BR83mvgyCIO5vLZaMwyD9wu3LtdzGAgescG4dfh8zEPwxBi9GLxXg%3D%3D%26mgm.logid%3Da2d03eb4-5cdb-11ec-ab35-a4bf0162964d%26mgm.blockchecksum%3Dignore%26mgm.replicaindex%3D0%26mgm.replicahead%3D0%26mgm.etag%3D%22665392374393864192:2fd03f71%22%26mgm.id%3D93bf2d6d%26mgm.mtime%3D1639182980]"}
```

3. The previous issue reported the DAV door was under an unbalanced load, on this case the door affected was balanced compared to the other ones serving the traffic.

**Comment by lemora** [comment] 2021-12-15 14:54
Hi Carlos.

Just to formally follow up: as discussed, it would be good if you could update transfermanager and the webdav doors to the newest bugfix version that is about to be released. Hopefully you can benefit from the recent fixes and improvements. Please let us know if these issues still persist!

Lea

**Comment by qiulan2021** [comment] 2022-01-04 22:13
Hello Lea,

After we upgrade to dcache-7.2.7-1, we still got the Early EOF error.

billing-error-2022.01.02:01.02 06:55:19 [door:WebDAV2-dcdoor10-2@webdav2-dcdoor10_httpsDomain:request] ["/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=atlpilo1/CN=614260/CN=Robot: ATLA
S Pilot1":6435:31152:130.199.149.175] [000087922889C4B841919509B91007E7825D,4240338293] [/pnfs/usatlas.bnl.gov/atlasscratchdisk/rucio/user/ssu/05/18/user.ssu.00340030.r10426_p3399_p3
850.27744148.out._000367.root.rucio.upload] scratchdisk:ATLAS@osm 33698 0 {10011:"Error relaying data: Early EOF"}
billing-error-2022.01.02:01.02 22:16:49 [door:WebDAV2-dcdoor17-2@webdav2-dcdoor17_httpsDomain:request] ["/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=atlpilo1/CN=614260/CN=Robot: ATLA
S Pilot1":6435:31152:130.199.157.47] [0000CEC827AC0D174FB99EAAD1F275C14BED,4254031193] [/pnfs/usatlas.bnl.gov/atlasscratchdisk/rucio/user/pfalke/ef/82/user.pfalke.27734388._000047.ou
tput.root.rucio.upload] scratchdisk:ATLAS@osm 30017 0 {10011:"Error relaying data: Early EOF"}
billing-error-2022.01.02:01.02 22:16:50 [door:WebDAV2-dcdoor07-2@webdav2-dcdoor07_httpsDomain:request] ["/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=atlpilo1/CN=614260/CN=Robot: ATLA
S Pilot1":6435:31152:130.199.157.47] [00002EBD1BB82C754479AAA08516DEDD0256,4195113214] [/pnfs/usatlas.bnl.gov/atlasscratchdisk/rucio/user/pfalke/59/fa/user.pfalke.27734388._000046.ou
tput.root.rucio.upload] scratchdisk:ATLAS@osm 28499 0 {10011:"Error relaying data: Early EOF"}
billing-error-2022.01.04:01.04 11:14:11 [door:WebDAV2-dcdoor14-2@webdav2-dcdoor14_httpsDomain:request] ["/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=atlpilo1/CN=614260/CN=Robot: ATLA
S Pilot1":6435:31152:130.199.159.9] [000096375D0AF93042AE82B711065467986B,4059179726] [/pnfs/usatlas.bnl.gov/atlasscratchdisk/rucio/user/doglioni/f8/b2/user.doglioni.27758697._000011
.tree.root.rucio.upload] scratchdisk:ATLAS@osm 4690 0 {10011:"Error relaying data: Early EOF"}
billing-error-2022.01.04:01.04 14:38:01 [door:WebDAV2-dcdoor09-2@webdav2-dcdoor09_httpsDomain:request] ["/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=atlpilo1/CN=614260/CN=Robot: ATLA
S Pilot1":6435:31152:130.199.159.137] [00007230DF8249264BB18CED77F4D5A84BD0,4076497808] [/pnfs/usatlas.bnl.gov/atlasscratchdisk/rucio/user/doglioni/40/a6/user.doglioni.27758467._0000
25.tree.root.rucio.upload] scratchdisk:ATLAS@osm 174 0 {10011:"Error relaying data: Early EOF"}


Do you give us some tips to get further investigation? Thanks.


Qiulan

**Comment by paulmillar** [comment] 2022-01-05 10:13
A few comments about the `Error relaying data: Early EOF` message.

This comes from the WebDAV door when it is proxying a transfer (either an upload or a download) and the client disconnects from the WebDAV door before that transfer completes.

Ignoring the possibility of bugs, the likely culprits are: overloaded BNL pool node, overloaded BNL-internal network, overloaded WebDAV door, overloaded WAN or client-side LAN, problems with recipient's storage.

If the problem is (predominately) with transfers that use one specific WebDAV door then that would be a natural place to start looking.  If this WebDAV door has an uneven percentage of the transfers (which seems to be the case) then it would be worth investigating why this is happening (clients not implementing DNS round-robin, badly configured load-balancer, ...)

**Comment by paulmillar** [comment] 2022-01-05 10:48
Some thoughts on the COPY request (your second post)

The access log file shows that the COPY was processed in 5897657 ms (98 minutes).  The access log entry was logged at 2021-12-14T09:23:11.019-0500, which means the transfer started at 2021-12-14T07:45-0500.  The timing of the preceding request (a HEAD request at 2021-12-14T07:44:53.332-0500) is consistent with this.


There are some interesting points in the FTS log file:
  1. The FTS log entry shows the transfer starting at 07:44:58.
  2. The next progress report shows data is flowing.
  3. At the point FTS aborted the transfer, the average bandwidth was ~260 KiB/s.
  4. The "instantaneous" bandwidth varies between 135 KiB/s and 417 KiB/s.
  5. There are some five places were FTS records "weird" information as progress reports.
 
The weird FTS information is potentially significant.  To generate the progress report for FTS, the WebDAV door will contact the pool (via the RemoteTransferAgent) to learn how many bytes have been transferred.  If the response is not received within a "reasonable" time (2.5 seconds, IIRC) then the door generates a minimal response, which is likely what is triggering the malformed FTS entries.

Therefore, it's possible that either the pool is overloaded, the RemoteTransferManager is overloaded, or there is a problem with BNL network.  Unfortunately, there's insufficient information to distinguish between these potential causes.

In any case, this is another example where a transfer failed because data was being transferred too slowly: at ~260 KiB/s on average.  The peak "instantaneous" bandwidth (averaged between two progress reports) was 417 KiB/s.

For comparison, the file being transferred is 2770231082 bytes (2.58 GiB) in size.  To transfer this file in 90 minutes (the apparent timeout) would require an average bandwidth of 501 KiB/s.

This isn't to say that the problem was with dCache or BNL hardware (it could be poor WAN networking or a problem with the remote site).  However, coupled with the apparent missing progress markers, I would have a look at the BNL networking to see if there's any indication of a problem there.

**Comment by lemora** [comment] 2022-01-05 11:03
Hi Qiulan.
Paul's assessment is already pretty thorough. Just a few further questions from my side, since this is not clear to me:
Issue #6389 only mentions that you updated the doors to 7.2.7, could you please confirm that you also updated the TransferManger? Is there still congestion on the RemoteTransferManager side, do you see similar messages to before in its logs (referring to ' too many transfers' or the like)?

**Comment by cfgamboa** [comment] 2022-01-05 14:44
Hi Lea,

Indeed the doors and SRM, TransferManager as well were updated to 7.2.7

All the best,
Carlos

**Comment by cfgamboa** [comment] 2022-03-16 12:57
Dear all,

We have observed FTS transfers like this one:
https://fts.usatlas.bnl.gov:8449/fts3/ftsmon/#/job/adc3e172-a466-11ec-be9f-00163e1051a1

Failing with the following error
```
INFO    Tue, 15 Mar 2022 09:52:15 -0400; [1647352335149] BOTH http_plugin	TRANSFER:EXIT	ERROR: Copy failed with mode 3rd pull, with error: Transfer failed: failure: rejected GET: 500 Server Error\n
INFO    Tue, 15 Mar 2022 09:52:15 -0400; [1647352335211] BOTH http_plugin	TRANSFER:EXIT	davs://webdav.aglt2.org:2880/atlasdatadisk/rucio/mc16_13TeV/fc/19/AOD.22751819._000052.pool.root.1?copy_mode=pull => https://dcdoor18.usatlas.bnl.gov:2881/upload/12/eac401f8-757c-4c7d-968c-59aa4a4643b4/AOD.22751819._000052.pool.root.1_1647352144
WARNING Tue, 15 Mar 2022 09:52:16 -0400; Timeout stopped
ERR     Tue, 15 Mar 2022 09:52:16 -0400; Recoverable error: [5] TRANSFER  ERROR: Copy failed with mode 3rd pull, with error: Transfer failed: failure: rejected GET: 500 Server Error\n
```

I the log at the door related error
```
webdav-dcdoor18_httpsDomain.access:level=WARN ts=2022-03-16T06:59:39.967-0400 event=org.dcache.webdav.request request.method=COPY request.url=https://dcdoor18.usatlas.bnl.gov:2881/upload/8/6c6cceaf-11c8-4e06-b669-3c264e7db5ec/AOD.22751819._001189.pool.root.1_1647426231 response.code=202 socket.remote=[2620:0:210:1::2d]:49170 user-agent="fts_url_copy/3.11.1 gfal2/2.20.2 neon/0.0.29" user.dn="CN=1647358203,CN=17783624,CN=1399668574,CN=Robot: ATLAS Data Management,CN=531497,CN=ddmadmin,OU=Users,OU=Organic Units,DC=cern,DC=ch" user.mapped=6435:31152,69907[7Gm+VblX:ROH+IJL9] tpc.credential=none tpc.error="rejected GET: 500 Server Error" tpc.require-checksum=false tpc.source=https://webdav.aglt2.org:2880/atlasdatadisk/rucio/mc16_13TeV/28/54/AOD.22751819._001189.pool.root.1?copy_mode=pull duration=187914
```

Is there any way to get more information from error " rejected GET: 500 Server Error" 

All the best,
Carlos

**Comment by paulmillar** [comment] 2022-03-16 18:59
Hi @cfgamboa ,

The error `Transfer failed: failure: rejected GET: 500 Server Error` indicates that the pool node successfully contacted the server (`webdav.aglt2.org` on port 2880) and issued a `GET` request targeting the file `/atlasdatadisk/rucio/mc16_13TeV/28/54/AOD.22751819._001189.pool.root.1`.  The remote server (`webdav.aglt2.org`) failed this request, responding with the status line `500 Server Error`.

Currently, we don't record any further details from the failed GET request (i.e., any response headers or entity).  Such response headers usually do not provide any useful information in understanding the problem, and the response body can be a web/HTML page, which wouldn't make sense to log.

So, prima facie, the problem was at AGLT2, as that site rejected the request (for some unspecified reason).

You can find out more information by contacting the admins at AGLT2 and asking them why their server rejected that GET request.

Cheers,
Paul.

**Comment by cfgamboa** [comment] 2022-03-17 20:07
Hello @paulmillar 
Thank you for the feedback. Parallel to your message we had contacted Aglt folks to follow up.

All the best,
Carlos

**Comment by paulmillar** [comment] 2022-03-17 22:43
OK, I guess we can close this issue.

(IIRC, the AGLT folks are using dCache, so they may wish to open their own issue ;-)

**Closed by paulmillar** 2022-03-17 22:43 UTC
